CREATE TABLE IF NOT EXISTS `drugs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `brand_name` varchar(255) DEFAULT NULL,
  `generic_name` varchar(255) DEFAULT NULL,
  `laboratory` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_drugs_on_brand_name` (`brand_name`),
  UNIQUE KEY `index_drugs_on_generic_name` (`generic_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10354 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO `drugs` (`id`, `brand_name`, `generic_name`, `laboratory`, `created_at`, `updated_at`) VALUES
	(4, 'Trout', 'Trout', 'Nelco Laboratories, Inc.', NULL, NULL),
	(14, 'Sodium Chloride', 'Sodium Chloride', 'Cardinal Health', NULL, NULL),
	(24, 'Mixed Vespid hymenoptera venom Venomil Maintenance', 'Mixed Vespid hymenoptera venom Venomil Maintenance', 'Jubilant HollisterStier LLC', NULL, NULL),
	(34, 'lisinopril', 'lisinopril', 'Physicians Total Care, Inc.', NULL, NULL),
	(44, 'Gerbil Epithelium', 'Gerbil Epithelium', 'Nelco Laboratories, Inc.', NULL, NULL),
	(54, 'SUNSCREEN STICK', 'Octinoxate,ZINC OXIDE,OCTISALATE', 'Yuyao Jessie Commodity Co.,Ltd.', NULL, NULL),
	(64, 'Bupropion Hydrochloride', 'bupropion hydrochloride', 'State of Florida DOH Central Pharmacy', NULL, NULL),
	(74, 'Lamotrigine', 'Lamotrigine', 'Glenmark Generics Inc., USA', NULL, NULL),
	(84, 'Mederma Advanced Scar', 'Allantoin', 'Merz Pharmaceuticals, LLC', NULL, NULL),
	(94, 'Clarithromycin', 'Clarithromycin', 'American Health Packaging', NULL, NULL),
	(104, 'Yellow Dock', 'Yellow Dock', 'Antigen Laboratories, Inc.', NULL, NULL),
	(114, 'ELIGARD', 'leuprolide acetate', 'sanofi-aventis U.S. LLC', NULL, NULL),
	(124, 'Common Sagebrush', 'Common Sagebrush', 'Nelco Laboratories, Inc.', NULL, NULL),
	(134, 'Maximum Strength Multi-Symptom Cold and Sinus', 'Acetaminophen, Guaifenesin, Phenylephrine HCl', 'ARMY AND AIR FORCE EXCHANGE SERVICE', NULL, NULL),
	(144, 'Soliris', 'eculizumab', 'Alexion Pharmaceuticals Inc.', NULL, NULL),
	(154, 'Germicida', 'Triclosan', 'Laboratorios Roldan, S.A.', NULL, NULL),
	(164, 'Chest Rub', 'Camphor, Eucalyptus Oil, Menthol', 'Valu Merchandisers, co', NULL, NULL),
	(174, 'Amoxicillin and Clavulanate Potassium', 'Amoxicillin and Clavulanate Potassium', 'Teva Pharmaceuticals USA Inc', NULL, NULL),
	(184, 'Atenolol and Chlorthalidone', 'atenolol and chlorthalidone', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(194, 'Cetirizine Hydrochloride', 'Cetirizine Hydrochloride', 'Sun Pharma Global FZE', NULL, NULL),
	(204, 'Headache', 'NITROGLYCERIN', 'Natural Health Supply', NULL, NULL),
	(224, 'Gablofen', 'baclofen', 'Mallinckrodt Inc (Brand Pharmaceuticals)', NULL, NULL),
	(234, 'LBEL COULEUR LUXE AMPLIFIER XP', 'Octinoxate and Oxybenzone', 'Ventura International LTD.', NULL, NULL),
	(244, 'phentermine hydrochloride', 'phentermine hydrochloride', 'Eon Labs, Inc.', NULL, NULL),
	(254, 'TIAZAC', 'diltiazem hydrochloride', 'Valeant Pharmaceuticals North America LLC', NULL, NULL),
	(264, 'Aspergillus terreus', 'Aspergillus terreus', 'Nelco Laboratories, Inc.', NULL, NULL),
	(274, 'Brioschi Childrens Effervescent Antacid', 'sodium bicarbonate, tartaric acid', 'Brioschi Pharmaceuticals International, LLC', NULL, NULL),
	(284, 'Nortriptyline Hydrochloride', 'Nortriptyline Hydrochloride', 'REMEDYREPACK INC.', NULL, NULL),
	(294, 'Broccoli', 'Broccoli', 'Nelco Laboratories, Inc.', NULL, NULL),
	(304, 'Veil Mineral Primer', 'Zinc Oxide, Titanium Dioxide', 'Kingdom Animalia, LLC, DBA Hourglass Cosmetics', NULL, NULL),
	(314, 'Fentanyl', 'fentanyl', 'Physicians Total Care, Inc.', NULL, NULL),
	(324, 'Oral HCG Homeopathic', 'Hypothalamus, Pituitary, Hepar Suis, Methyl B12', 'ABCO Laboratories, Inc.', NULL, NULL),
	(334, 'MINERAL OIL, PRAMOXINE HYDROCHLORIDE AND ZINC OXIDE', 'MINERAL OIL, PRAMOXINE HYDROCHLORIDE AND ZINC OXIDE', 'CVS Pharmacy', NULL, NULL),
	(344, 'Gemfibrozil', 'Gemfibrozil', 'Med-Health Pharma, LLC', NULL, NULL),
	(354, 'Vagi Soothe', 'Kreosotum, Merc sol, Lycopodium , Calc carb, Sepia', 'Feelgood Health', NULL, NULL),
	(364, 'Aztreonam', 'AZTREONAM', 'Fresenius Kabi USA, LLC', NULL, NULL),
	(374, 'SUN DEFENSE SPF 15', 'AVOBENZONE HOMOSALATE OCTISALATE OXYBENZONE', 'Kamins Dermatologics Inc.', NULL, NULL),
	(384, 'Mucus Relief DM', 'Dextromethorphan HBr and Guiafenesin', 'NASH-FINCH COMPANY', NULL, NULL),
	(394, 'Golden Sunshine Far Infrared Herbal', 'Topical Analgesic', 'Golden Sunshine International, Inc.', NULL, NULL),
	(404, 'Sonacaine Topical Anesthetic With Menthol', 'LIDOCAINE', 'Filltech USA, LLC', NULL, NULL),
	(414, 'HydrALAZINE Hydrochloride', 'HydrALAZINE Hydrochloride', 'Strides Arcolab Limited', NULL, NULL),
	(424, 'Alprazolam', 'Alprazolam', 'Amneal Pharmaceuticals, LLC', NULL, NULL),
	(434, 'Foam Hand Sanitizer', 'Alcohol', 'Rubbermaid Commercial Products LLC', NULL, NULL),
	(444, 'cold and cough nighttime', 'Acetaminophen, Dextromethorphan HBr, Doxylamine Succinate', 'CVS Pharmacy', NULL, NULL),
	(454, 'Parrot Head Fins Up Sport 30 Mist', 'avobenzone, homosalate, octisalate, octocrylene', 'Sun & Skin Care Research, Inc', NULL, NULL),
	(464, 'Lovastatin', 'Lovastatin', 'REMEDYREPACK INC.', NULL, NULL),
	(474, 'No7 Soft and Sheer Tinted Moisturiser Medium', 'Octinoxate and Titanium Dioxide', 'Boots Retail USA Inc', NULL, NULL),
	(484, 'Pioglitazone', 'pioglitazone', 'Mylan Institutional Inc.', NULL, NULL),
	(494, 'Multi Vitamin Infusion Adult', 'RETINOL, ERGOCALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, DL-, PHYTONADIONE, ASCORBIC ACID, NIACINAMIDE, RIBOFLAVIN 5-PHOSPHATE SODIUM, THIAMINE HYDROCHLORIDE, PYRIDOXINE HYDROCHLORIDE, DEXPANTHENOL, BIOTIN, FOLIC ACID, and CYANOCOBALAMIN', 'Hospira Worldwide, Inc.', NULL, NULL),
	(504, 'Cefdinir', 'Cefdinir', 'LUPIN PHARMACEUTICALS INC', NULL, NULL),
	(514, 'HYDROCORTISONE', 'HYDROCORTISONE', 'CVS Pharmacy', NULL, NULL),
	(524, 'CLARINS Broad Spectrum SPF 15 Titanium Dioxide-Sunscreen Extra-Firming Foundation Tint 105', 'TITANIUM DIOXIDE', 'Laboratoires Clarins S.A.', NULL, NULL),
	(534, 'Amoebatox', 'Triticum aestivum, Baptisia tinctoria Capsicum anuum, Columbo, Fragaria vesca, Hamamelis virginiana, Hydrastis canadensis, Quassia amara, Senna, Liver, Pancreas, Spleen, Belladonna, Cinchona officinal', 'Apotheca Company', NULL, NULL),
	(544, 'Dronabinol', 'Dronabinol', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(554, 'Warfarin Sodium', 'Warfarin Sodium', 'Aidarex Pharmaceuticals LLC', NULL, NULL),
	(564, 'ZENPEP', 'pancrelipase', 'Aptalis Pharma US, Inc.', NULL, NULL),
	(574, 'ACID REDUCER', 'Ranitidine', 'Chain Drug Marketing Association Inc.', NULL, NULL),
	(584, 'GB-Tone', 'Homeopathic Liquid', 'Energetix Corp', NULL, NULL),
	(594, 'ASTAGRAF XL', 'tacrolimus extended-release capsules', 'Astellas Pharma US, Inc.', NULL, NULL),
	(604, 'Duck Feathers', 'Duck Feathers', 'Nelco Laboratories, Inc.', NULL, NULL),
	(614, 'Head and Shoulders Conditioner', 'Pyrithione Zinc', 'Procter & Gamble Manufacturing Co.', NULL, NULL),
	(624, 'Ciprofloxacin', 'Ciprofloxacin', 'ReadyMeds', NULL, NULL),
	(634, 'Ondansetron', 'Ondansetron', 'Glenmark Generics Inc., USA', NULL, NULL),
	(644, 'Paroxetine', 'Paroxetine Hydrochloride', 'Rebel Distributors Corp', NULL, NULL),
	(654, 'HCB-Tone', 'Heart Muscle Aid', 'Vitality Works, Inc.', NULL, NULL),
	(674, 'Povidone-Iodine', 'Povidone-Iodine', 'Smiths Medical ASD, INC', NULL, NULL),
	(694, 'SODIUM SULFACETAMIDE', 'SODIUM SULFACETAMIDE', 'BioComp Pharma, Inc.', NULL, NULL),
	(704, 'Allerstat', 'Baptisia tinctoria, Echinacea (angustifolia), Allium cepa, Ambrosia artemisiaefolia, Arsenicum album, Euphrasia officinalis, Natrum sulphuricum,', 'Energique, Inc.', NULL, NULL),
	(714, 'SINGULAIR', 'montelukast sodium', 'Dispensing Solutions Inc.', NULL, NULL),
	(724, 'COREG', 'carvedilol phosphate', 'Carilion Materials Management', NULL, NULL),
	(734, 'Canary Grass', 'Canary Grass', 'Nelco Laboratories, Inc.', NULL, NULL),
	(744, 'Diclofenac Sodium and Misoprostol', 'Diclofenac Sodium and Misoprostol', 'BluePoint Laboratories', NULL, NULL),
	(754, 'Lorazepam', 'Lorazepam', 'Rebel Distributors Corp', NULL, NULL),
	(764, 'Food - Plant Source, Carrot Daucus carota', 'Carrot Daucus carota', 'Jubilant HollisterStier LLC', NULL, NULL),
	(774, 'REPREXAIN', 'Hydrocodone Bitartrate and Ibuprofen', 'Quinnova Pharmaceuticals, LLC', NULL, NULL),
	(784, 'Quik Wipes', 'Advanced Hand Sanitizing Wipes', 'Cinogen Cosmetics Zhaoqing, LTD.', NULL, NULL),
	(794, 'Octreotide', 'OCTREOTIDE ACETATE', 'Fresenius Kabi USA, LLC', NULL, NULL),
	(804, 'Slash Pine', 'Slash Pine', 'Nelco Laboratories, Inc.', NULL, NULL),
	(814, 'Dexmethylphenidate Hydrochloride', 'dexmethylphenidate hydrochloride', 'Sandoz Inc', NULL, NULL),
	(824, 'Cyclobenzaprine Hydrochloride', 'Cyclobenzaprine Hydrochloride', 'Preferred Pharmaceuticals, Inc.', NULL, NULL),
	(834, 'acetaminophen', 'Acetaminophen', 'Kroger Company', NULL, NULL),
	(854, 'Hourglass Illusion Tinted Moisturizer Warm Beige', 'OCTINOXATE, OCTISALATE, TITANIUM DIOXIDE', 'Kingdom Animalia, LLC DBA Hourglass Cosmetics', NULL, NULL),
	(864, 'Ibuprofen', 'Ibuprofen', 'Wal-Mart Stores Inc', NULL, NULL),
	(874, 'Watermelon', 'Watermelon', 'Nelco Laboratories, Inc.', NULL, NULL),
	(894, 'Smart Sense Acid Reducer', 'Lansoprazole', 'Kmart Corporation', NULL, NULL),
	(904, 'Simvastatin', 'Simvastatin', 'Dr. Reddy\'s Laboratories Limited', NULL, NULL),
	(914, 'Pork', 'Pork', 'Nelco Laboratories, Inc.', NULL, NULL),
	(924, 'E.O.L.', 'Stillingia Sylvatica, Zincum Gluconicum, Thiaminum Hydrochloricum, Fragaria Vescus, Niacin, Serotonin (Hydrochloride), 5-Hydroxytryptophan, Betainum Muriaticum', 'InLight Creation, LLC.', NULL, NULL),
	(934, 'Arnica Plus', 'Arnia montana, Hamamelis virginiana, Rhus toxicodendron,', 'Apotheca Company', NULL, NULL),
	(944, 'Diclofenac Potassium', 'diclofenac potassium', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', NULL, NULL),
	(964, 'TACLONEX', 'calcipotriene and betamethasone dipropionate', 'LEO Pharma Inc.', NULL, NULL),
	(974, 'K Phos', 'Sodium Phosphate, Dibasic, Anhydrous, Potassium Phosphate, Monobasic, and Sodium Phosphate, Monobasic, Monohydrate', 'Beach Productsd, Inc.', NULL, NULL),
	(984, 'Ferrum Quartz Headache Relief Pellets', 'IRON SANGUINARIA CANADENSIS SULFUR SILICON DIOXIDE', 'Uriel Pharmacy Inc', NULL, NULL),
	(994, 'Nice and Clean Antibacterial', 'Benzalkonium Chloride', 'Professional Disposables International, Inc.', NULL, NULL),
	(1004, 'Health Mart Maximum Strength Sleep Aid', 'DIPHENHYDRAMINE HYDROCHLORIDE', 'McKesson', NULL, NULL),
	(1014, 'Huo Pao Tieh Ta Feng Shin Kao', 'L-Menthol, Camphor', 'Dah Wei Biochemical Pharmaceutic International Ltd.', NULL, NULL),
	(1024, 'Chem - Tox', 'Adrenal, Arctium lappa, ATP, Belladonna, Chemical isodes', 'ABCO Laboratories, Inc.', NULL, NULL),
	(1034, 'GEM BEAUTY AMETHYST PERFECT SOLUTION BB CREAM', 'ALOE FEROX LEAF', 'GEMPARK CO LTD', NULL, NULL),
	(1044, 'PINUS ECHINATA POLLEN', 'Pine Yellow', 'ALK-Abello, Inc.', NULL, NULL),
	(1054, 'Nitrofurantoin Macrocrystals', 'Nitrofurantoin Macrocrystals', 'BluePoint Laboratories', NULL, NULL),
	(1064, 'Diathesis', 'Pancreas, Spleen, Stomach, Ginkgo biloba, Germanium sesquioxide, Cuprum metallicum', 'Apotheca Company', NULL, NULL),
	(1074, 'PRENATAL PLUS', 'VITAMIN A ACETATE, .BETA.-CAROTENE, ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, DL-, THIAMINE MONONITRATE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE HYDROCHLORIDE, FOLIC ACID, CYANOCOBALAMIN, CALCIUM CARBONATE, FERROUS FUMARATE, ZINC OXIDE, CUPR', 'Carilion Materials Management', NULL, NULL),
	(1084, 'Amlodipine besylate and Atorvastatin calcium', 'amlodipine besylate and atorvastatin calcium', 'Greenstone LLC', NULL, NULL),
	(1094, 'Normosol-M and Dextrose', 'DEXTROSE MONOHYDRATE, SODIUM CHLORIDE, POTASSIUM ACETATE, and MAGNESIUM ACETATE', 'Hospira, Inc.', NULL, NULL),
	(1104, 'Doxazosin', 'Doxazosin', 'St Marys Medical Park Pharmacy', NULL, NULL),
	(1114, 'Sperian Eyesaline Eyewash', 'Water', 'Sperian Eye & Face Protection Inc', NULL, NULL),
	(1124, 'Broad Spectrum SPF 50 Kids', 'Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', 'Kinray Inc.', NULL, NULL),
	(1134, 'Lamivudine', 'Lamivudine', 'American Health Packaging', NULL, NULL),
	(1144, 'Diaper Rash', 'Zinc oxide', 'Harmon Stores Inc', NULL, NULL),
	(1154, 'PRAMIPEXOLE DIHYDROCHLORIDE', 'PRAMIPEXOLE DIHYDROCHLORIDE', 'American Health Packaging', NULL, NULL),
	(1164, 'Citalopram Hydrobromide', 'Citalopram Hydrobromide', 'NCS HealthCare of KY, Inc dba Vangard Labs', NULL, NULL),
	(1174, 'Amlodipine Besylate', 'amlodipine besylate', 'Mylan Institutional Inc.', NULL, NULL),
	(1184, 'butalbital and acetaminophen', 'butalbital and acetaminophen', 'Qualitest Pharmaceuticals', NULL, NULL),
	(1194, 'Bipolaris sorokiniana', 'Bipolaris sorokiniana', 'Nelco Laboratories, Inc.', NULL, NULL),
	(1204, 'Zodryl DEC 50', 'codeine phosphate, guaifenesin and pseudoephedrine hydrochloride', 'CodaDose, Inc.', NULL, NULL),
	(1214, 'Etodolac', 'Etodolac', 'Unit Dose Services', NULL, NULL),
	(1224, 'Burweed Marsh Elder', 'Burweed Marsh Elder', 'Nelco Laboratories, Inc.', NULL, NULL),
	(1234, 'Xarelto', 'rivaroxaban', 'Janssen Pharmaceuticals, Inc.', NULL, NULL),
	(1244, 'CeraVe', 'Homosalate, Octinoxate, Zinc Oxide, and Octocrylene', 'Valeant Pharmaceuticals North America LLC', NULL, NULL),
	(1254, 'Arsuraneel', 'TUBOCURARINE CHLORIDE and CINCHONA OFFICINALIS BARK and STRYCHNINE NITRATE and MARSDENIA CONDURANGO BARK and CLAVICEPS PURPUREA SCLEROTIUM and ACETIC ACID and PHOSPHORIC ACID and ARSENIC TRIOXIDE', 'Heel Inc', NULL, NULL),
	(1264, 'MEIJER SPF 4 TANNING OIL', 'OCTINOXATE, PADIMATE O', 'Meijer Distribution Inc', NULL, NULL),
	(1274, 'Chinese Elm', 'Chinese Elm', 'Nelco Laboratories, Inc.', NULL, NULL),
	(1284, 'Oxybutynin Chloride', 'oxybutynin chloride', 'NCS HealthCare of KY, Inc dba Vangard Labs', NULL, NULL),
	(1294, 'Depo-Provera', 'medroxyprogesterone acetate', 'Pharmacia and Upjohn Company', NULL, NULL),
	(1304, 'Lil Drug Store Cold Relief', 'Acetaminophen, Dextromethorphan Hydrobromide, Guaifenesin, and Phenylephrine Hydrochloride', 'Lil\' Drug Store Products, Inc.', NULL, NULL),
	(1314, 'Nasotuss', 'Chlorcyclizine Hydrochloride, Codeine Phosphate, Phenylephrine Hydrochloride', 'Hawthorn Pharmaceuticals, Inc.', NULL, NULL),
	(1324, 'Hydrochlorothiazide', 'Hydrochlorothiazide', 'Accord Healthcare Inc.', NULL, NULL),
	(1334, 'Monistat 7', 'Miconazole Nitrate', 'Insight Pharmaceuticals', NULL, NULL),
	(1344, 'Crest 3D White', 'Sodium Fluoride', 'The Procter & Gamble Manufacturing Company', NULL, NULL),
	(1354, 'SNAYTOX', 'DIMETHICONE', 'NATURE REPUBLIC CO., LTD.', NULL, NULL),
	(1364, 'Secret Clinical Strength', 'ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY', 'Procter & Gamble Manufacturing Company', NULL, NULL),
	(1374, 'Sally Hansen', 'Undecylenic Acid', 'Coty US LLC', NULL, NULL),
	(1384, 'Jason Pure Natural Sun Mineral Natural Sunscreen Broad Spectrum SPF30', 'Zinc Oxide, Titanium Oxide', 'The Hain Celestial Group, Inc.', NULL, NULL),
	(1394, 'LBEL EFFET PARFAIT filling effect foundation SPF 10 - CLAIRE 4', 'Octinoxate', 'Ventura Corporation LTD.', NULL, NULL),
	(1404, 'Australian Pine Pollen', 'Casuarina equisetifoli', 'Allermed Laboratories, Inc.', NULL, NULL),
	(1414, 'Diazepam', 'diazepam', 'Unit Dose Services', NULL, NULL),
	(1424, 'DICYCLOMINE', 'DICYCLOMINE HYDROCHLORIDE', 'STAT RX USA LLC', NULL, NULL),
	(1464, 'Metronidazole', 'Metronidazole', 'UDL Laboratories, Inc.', NULL, NULL),
	(1474, 'Travoprost Ophthalmic Solution 0.004%', 'travoprost', 'Par Pharmaceutical, Inc.', NULL, NULL),
	(1484, 'Metoclopramide Hydrochloride', 'Metoclopramide Hydrochloride', 'Aphena Pharma Solutions - Tennessee, LLC', NULL, NULL),
	(1494, 'Rivastigmine Tartrate', 'Rivastigmine Tartrate', 'Dr.Reddy\'s Laboratories Limited', NULL, NULL),
	(1514, 'Guinea Pig Epithelium', 'Guinea Pig Epithelium', 'Nelco Laboratories, Inc.', NULL, NULL),
	(1524, 'Cefuroxime and Dextrose', 'CEFUROXIME AND DEXTROSE', 'B. Braun Medical Inc.', NULL, NULL),
	(1534, 'CISplatin', 'CISplatin', 'WG Critical Care, LLC', NULL, NULL),
	(1544, 'Perfectionism', 'Aceticum acidum, Borago officinalis, Cereus bonplandii, Cyclamen europaeum, Ignatia amara, Passiflora incarnata, Silicea, Sinapis arvensis, flos, Spiraea ulmaria, Staphysagria, Strontium carbonicum, Tropaeolum majus', 'King Bio Inc.', NULL, NULL),
	(1554, 'Lidocaine Hydrochloride', 'LIDOCAINE HYDROCHLORIDE ANHYDROUS', 'McKesson Packaging Services Business Unit of McKesson Corporation', NULL, NULL),
	(1564, 'AMOXICILLIN', 'AMOXICILLIN', 'DIRECT RX', NULL, NULL),
	(1574, 'Chlordiazepoxide Hydrochloride', 'Chlordiazepoxide Hydrochloride', 'AvKARE, Inc.', NULL, NULL),
	(1584, 'Methylphenidate Hydrochloride', 'Methylphenidate Hydrochloride', 'Actavis South Atlantic LLC', NULL, NULL),
	(1594, 'equaline night time cold and cough', 'Diphenhydramine HCl, Phenylephrine HCl', 'Supervalu Inc', NULL, NULL),
	(1604, 'Atenolol', 'atenolol', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(1614, 'Duloxetine', 'Duloxetine', 'Cadila Healthcare Limited', NULL, NULL),
	(1634, 'Treatment Set TS329894', 'Treatment Set TS329894', 'Antigen Laboratories, Inc.', NULL, NULL),
	(1644, 'Cold Multi-Symptom Daytime', 'Acetaminophen, Phenylephrine HCl and Dextromethorphan HBr', 'Wal-Mart Stores Inc', NULL, NULL),
	(1654, 'Venlafaxine Hydrochloride', 'Venlafaxine Hydrochloride', 'Bryant Ranch Prepack', NULL, NULL),
	(1684, 'Capecitabine', 'Capecitabine', 'Teva Pharmaceuticals USA Inc', NULL, NULL),
	(1694, 'Mirtazapine', 'Mirtazapine', 'Mylan Institutional Inc.', NULL, NULL),
	(1704, 'DONEPEZIL HYDROCHLORIDE', 'DONEPEZIL HYDROCHLORIDE', 'Cardinal Health', NULL, NULL),
	(1714, 'Doxycycline Hyclate', 'Doxycycline Hyclate', 'Citron Pharma LLC', NULL, NULL),
	(1724, 'Venlafaxine', 'Venlafaxine', 'Qualitest Pharmaceuticals', NULL, NULL),
	(1734, 'clearskin', 'salicylic acid', 'Avon Products, Inc.', NULL, NULL),
	(1744, 'Naproxen', 'Naproxen', 'Sandoz Inc', NULL, NULL),
	(1754, 'CPDA-1', 'Anticoagulant Citrate Phosphate Dextrose Adenine', 'Fenwal, Inc.', NULL, NULL),
	(1784, 'Nitrous Oxide', 'Nitrous Oxide', 'WestAir Gases & Equipment, Inc.', NULL, NULL),
	(1804, 'Risperidone', 'risperidone', 'REMEDYREPACK INC.', NULL, NULL),
	(1844, 'Cucumber', 'Cucumber', 'Nelco Laboratories, Inc.', NULL, NULL),
	(1854, 'Energise RxS', 'Sarcolacticum Acidum, Viscum Album, Iodium, Colchicum Atumnale, Conium Maculatum, Fucus Vesiculosus, Galiu Aparine, Natrum Oxalaceticum', 'Deseret Biologicals', NULL, NULL),
	(1864, 'TORSEMIDE', 'TORSEMIDE', 'Roxane Laboratories, Inc', NULL, NULL),
	(1884, 'Midodrine Hydrochloride', 'midodrine hydrochloride', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(1894, 'Iron Mix', 'Phenylalanine, Quercetin, Rutin, Ascorbic acid, Ferrum metallicum, Ferrum muriaticum, Ferrum phosphoricum, Ferrum sulphuricum, Sarcolacticum acidum,', 'Deseret Biologicals, Inc.', NULL, NULL),
	(1904, 'White Pine', 'White Pine', 'Nelco Laboratories, Inc.', NULL, NULL),
	(1914, 'aspirin', 'Aspirin', 'Publix Super Markets Inc', NULL, NULL),
	(1934, 'Equate Pain Relieving', 'Camphor, Menthol, Methyl salicylate', 'Wal-Mart Stores Inc', NULL, NULL),
	(1954, 'Pep-Back', 'Caffeine', 'Alva-Amco Pharmacal Companies, Inc.', NULL, NULL),
	(1964, 'Carbo Prunus comp. Special Order', 'Carbo Prunus comp. Special Order', 'Uriel Pharmacy Inc.', NULL, NULL),
	(1974, 'Ibuprofen and Pseudoephedrine Hydrochloride', 'Ibuprofen and Pseudoephedrine Hydrochloride', 'Sunmark', NULL, NULL),
	(1984, 'Cefuroxime Axetil', 'Cefuroxime Axetil', 'Gen-Source Rx', NULL, NULL),
	(1994, 'Appeal Alcohol Foaming Hand Sanitizer', 'Ethyl Alcohol', 'Deb USA, Inc.', NULL, NULL),
	(2004, 'Gabapentin', 'GABAPENTIN', 'Solco healthcare U.S., LLC', NULL, NULL),
	(2034, 'Trichoderma harzianam', 'Trichoderma harzianam', 'Nelco Laboratories, Inc.', NULL, NULL),
	(2054, 'HEPAR SULPH. CALC.', 'CALCIUM SULFIDE', 'Hyland\'s', NULL, NULL),
	(2064, 'Vivelle Dot', 'estradiol', 'Physicians Total Care, Inc.', NULL, NULL),
	(2084, 'Body', 'Menthol, zinc oxide', 'Exchange Select', NULL, NULL),
	(2094, 'Carvedilol', 'Carvedilol', 'Northwind Pharmaceuticals', NULL, NULL),
	(2124, 'Grain and Seed Antigen', 'Barley, Oats, Wheat, Rice, Rye, Millet, Soybean, Corn, Milo, Bamboo, Cotton seed, Flax seed,', 'Apotheca Company', NULL, NULL),
	(2134, 'SQUASH', 'Squash', 'ALK-Abello, Inc.', NULL, NULL),
	(2144, 'Metformin Hydrochloride', 'Metformin Hydrochloride', 'Blu Pharmaceuticals, LLC', NULL, NULL),
	(2154, 'Super CC Plus Concealer', 'Titanium Dioxide, Zinc Oxide', 'Physicians Formula Inc', NULL, NULL),
	(2164, 'ARANESP', 'darbepoetin alfa', 'Amgen Inc', NULL, NULL),
	(2174, 'Amazing Grace Antiperspirant and Deodorant', 'Aluminum Zirconium Tetrachlorohydrex gly', 'Raani Corporation', NULL, NULL),
	(2214, 'Butrans', 'buprenorphine', 'A-S Medication Solutions LLC', NULL, NULL),
	(2224, 'Protamine Sulfate', 'PROTAMINE SULFATE', 'Cardinal Health', NULL, NULL),
	(2234, 'chempace SANI-GEL INSTANT SKIN SANITIZER', 'ethanol', 'Chempace Corporation', NULL, NULL),
	(2244, 'Emotional Eating', 'Thyroidinum (suis), Cortisone aceticum, Anacardium orientale, Antimonium crudum, Ignatia amara, Natrum muriaticum, Staphysagria, Hydrocortisone (cortisol).', 'Dr. Donna Restivo DC', NULL, NULL),
	(2254, 'Fluorouracil', 'Fluorouracil', 'Taro Pharmaceuticals U.S.A., Inc.', NULL, NULL),
	(2264, 'Bismuth Subsalicylate', 'Bismuth Subsalicylate', 'A&Z Pharmaceutical, Inc.', NULL, NULL),
	(2274, 'Cyclopentolate Hydrochloride', 'Cyclopentolate Hydrochloride', 'Falcon Pharmaceuticals, Ltd.', NULL, NULL),
	(2294, 'Oxygen', 'Oxygen', 'Terjan Co., Inc. DBA Valley Welding Supply Company', NULL, NULL),
	(2304, 'Cerebraplex', 'Avena Sativa, Capsicum Annuum, Ginkgo Biloba, Hydrocotyle Asiatica, Polygonum Multiflorum, Rosmarinus Officinalis, Vinca Minor, Brain (Suis)', 'BioActive Nutritional, Inc.', NULL, NULL),
	(2314, 'ropinirole hydrochloride', 'ropinirole hydrochloride', 'Zydus Pharmaceuticals (USA) Inc.', NULL, NULL),
	(2334, 'Cut Care Alcohol Prep Pad', 'Isopropyl alcohol', 'Zeus Medical Holdings LLC', NULL, NULL),
	(2344, 'Ribavirin', 'Ribavirin', 'Aurobindo Pharma Limited', NULL, NULL),
	(2364, 'Levofloxacin', 'Levofloxacin', 'REMEDYREPACK INC.', NULL, NULL),
	(2374, 'Fenofibrate', 'Fenofibrate', 'Dr. Reddy\'s Laboratories Limited', NULL, NULL),
	(2394, 'Travel Remedy', 'PRIMULA VERIS EXTRACT ONOPORDUM HYOSCYAMUS NIGER ANTIMONY GOLD ARNICA MONTANA BELLIS PERENNIS MATRICARIA RECUTITA IPECAC LYCOPODIUM CLAVATUM SPORE', 'Uriel Pharmacy Inc', NULL, NULL),
	(2414, 'Day Time Sinus', 'Acetaminophen and Phenylephrine Hydrochloride', 'Freds Inc', NULL, NULL),
	(2434, 'Zonisamide', 'Zonisamide', 'Camber Pharmaceuticals', NULL, NULL),
	(2444, 'Neomycin and Polymyxin B Sulfates and Dexamethasone', 'neomycin sulfate, polymyxin B sulfate and dexamethasone', 'Rebel Distributors Corp', NULL, NULL),
	(2454, 'Treatment Set TS332147', 'Treatment Set TS332147', 'Antigen Laboratories, Inc.', NULL, NULL),
	(2464, 'Secale Cornutum Kit Refill', 'CLAVICEPS PURPUREA SCLEROTIUM', 'Washington Homeopathic Products', NULL, NULL),
	(2474, 'Labetalol Hydrochloride', 'Labetalol Hydrochloride', 'Physicians Total Care, Inc.', NULL, NULL),
	(2494, 'DR WALTONS PETROLEUM', 'PETROLATUM', 'Dr. Waltons, Incorporated', NULL, NULL),
	(2504, 'Ramipril', 'Ramipril', 'Northwind Pharmaceuticals', NULL, NULL),
	(2514, 'Glipizide', 'Glipizide', 'Par Pharmaceutical', NULL, NULL),
	(2524, 'Neutrogena Clear Face Break Out Free', 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'Neutrogena Corporation', NULL, NULL),
	(2534, 'Quinapril Hydrochloride and Hydrochlorothiazide', 'Quinapril Hydrochloride and Hydrochlorothiazide', 'Apotex Corp', NULL, NULL),
	(2554, 'Precose', 'Acarbose', 'Bayer HealthCare Pharmaceuticals Inc.', NULL, NULL),
	(2574, 'RIXUBIS', 'COAGULATION FACTOR IX RECOMBINANT HUMAN', 'Baxter Healthcare Corporation', NULL, NULL),
	(2594, 'Orajel Instant Pain Relief', 'Benzocaine 20%', 'Church & Dwight Co., Inc.', NULL, NULL),
	(2604, 'Ampicillin', 'Ampicillin Sodium', 'Sandoz Inc', NULL, NULL),
	(2634, 'Pleo Fort', 'penicillium roqueforti', 'Sanum Kehlbeck GmbH & Co. KG', NULL, NULL),
	(2644, 'Acne Cystic Acne', 'Antimon. crud., Arsenicum alb., Aur. met., Berber. aqui., Bovista, Carbo veg., Causticum, Chelidonium majus, Dulcamara, Graphites, Hepar sulph. calc., Hydrocotyle, Kali brom., Kali iod., Ledum, Lycopodium, Nux vom., Silicea, Sulphur iod., Zinc. met., Echi', 'Newton Laboratories, Inc.', NULL, NULL),
	(2664, 'hydrocodone bitartrate and acetaminophen', 'hydrocodone bitartrate and acetaminophen', 'bryant ranch prepack', NULL, NULL),
	(2684, 'Smart Sense Hemorrhoidal', 'cocoa butter, phenylephrine hcl', 'Kmart Corporation', NULL, NULL),
	(2694, 'laura mercier Tinted Moisturizer Creme Compact Broad Spectrum SPF 20 Sunscreen FAWN', 'AVOBENZONE, OCTISALATE, OCTOCRYLENE', 'Gurwitch Products', NULL, NULL),
	(2704, 'Oxsoralen-Ultra', 'Methoxsalen', 'Valeant Pharmaceuticals North America LLC', NULL, NULL),
	(2714, 'Esmolol Hydrochloride', 'esmolol hydrochloride', 'Mylan Institutional LLC', NULL, NULL),
	(2724, 'Good Neighbor Pharmacy Nicotine', 'Nicotine Polacrilex', 'Amerisource Bergen', NULL, NULL),
	(2734, 'SunscreenSPF 30', 'Octinoxate, Octisalate, Oxybenzone, Titanium Dioxide', 'Ningbo Dowland Daily Health Co., Ltd', NULL, NULL),
	(2754, 'Pure Petroleum Cocoa Butter Scented', 'White Petroleum', 'Singhfam Corporation.', NULL, NULL),
	(2764, 'PerioMed', 'stannous fluoride', '3M ESPE Dental Products', NULL, NULL),
	(2794, 'Arnica Scorodite', 'Arnica Scorodite', 'Uriel Pharmacy Inc.', NULL, NULL),
	(2804, 'MANGO BEBE LIP ESSENCE', 'OCTINOXATE, OCTISALATE', 'NATURE REPUBLIC CO., LTD.', NULL, NULL),
	(2814, 'Broad Spectrum SPF 15 Daily Eye Treat', 'Avobenzone, Homosalate, Octisalate, Octoorylene', 'JAFRA COSMETICS INTERNATIONAL', NULL, NULL),
	(2824, 'Propranolol Hydrochloride', 'Propranolol Hydrochloride', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', NULL, NULL),
	(2834, 'Ban', 'Aluminum Chlorohydrate', 'Kao Brands Company', NULL, NULL),
	(2844, 'Cough Relief', 'Natural Medicine', 'King Bio Inc.', NULL, NULL),
	(2854, 'PEN Prep Plus', 'MAGNESIUM CITRATE', 'PEN Prep LLC', NULL, NULL),
	(2864, 'Acetaminophen And Codeine Phosphate', 'acetaminophen and codeine phosphate', 'Mckesson Packaging Services a business unit of McKesson Corporation', NULL, NULL),
	(2874, 'Good Sense Milk of Magnesia', 'Magnesium hydroxide', 'L. Perrigo Company', NULL, NULL),
	(2914, 'GAVISCON', 'aluminum hydroxide and magnesium carbonate', 'GlaxoSmithKline Consumer Healthcare LP', NULL, NULL),
	(2924, 'Sleep-Aid', 'Doxylamine succinate', 'H E B', NULL, NULL),
	(2934, 'SKINFOOD CACAO HAND BALM', 'GLYCERIN', 'SKINFOOD CO., LTD.', NULL, NULL),
	(2944, 'MD-76R', 'Diatrizoate meglumine and Diatrizoate sodium', 'Mallinckrodt Inc.', NULL, NULL),
	(2954, 'Gilotrif', 'afatinib', 'Boehringer Ingelheim Pharmaceuticals, Inc.', NULL, NULL),
	(2964, 'Econazole Nitrate', 'Econazole Nitrate', 'Taro Pharmaceuticals U.S.A., Inc.', NULL, NULL),
	(2974, 'Arixtra', 'fondaparinux sodium', 'Mylan Institutional LLC', NULL, NULL),
	(2984, 'gas relief', 'Simethicone', 'Walgreen Company', NULL, NULL),
	(3004, 'Duck Meat', 'Duck Meat', 'Nelco Laboratories, Inc.', NULL, NULL),
	(3024, 'Cyclophosphamide', 'Cyclophosphamide', 'Roxane Laboratories, Inc', NULL, NULL),
	(3044, 'Cough - Asthma', 'Influenza A Virus, Influenza B Virus, Antimon. tart., Arsenicum alb., Bryonia, Chelidonium majus, Cinchona, Drosera, Eucalyptus, Histaminum hydrochloricum, Hydrastis, Kali bic., Kali carb.,Kali iod., Myrrha, Nat. sulphuricum, Nux vom., Phosphorus, Pulsati', 'Newton Laboratories, Inc.', NULL, NULL),
	(3064, 'Dandelion', 'Dandelion', 'Nelco Laboratories, Inc.', NULL, NULL),
	(3084, 'Terrasil Wound Care', 'Allantoin, Benzethonium Chloride', 'Aidance Skincare & Topical Solutions, LLC', NULL, NULL),
	(3104, 'Mark 3', 'Benzocaine', 'Cargus International, Inc.', NULL, NULL),
	(3114, 'Extra Strength Pain Relief Therapy', 'Menthol', 'United Exchange Corp', NULL, NULL),
	(3134, 'Standardized Grass Pollen, Bluegrass, Kentucky (June)', 'Standardized Grass Pollen, Bluegrass, Kentucky (June)', 'Jubilant HollisterStier LLC', NULL, NULL),
	(3144, 'Prednisone', 'Prednisone', 'Hikma Pharmaceutical', NULL, NULL),
	(3164, 'Dexamethasone', 'Dexamethasone', 'A-S Medication Solutions LLC', NULL, NULL),
	(3174, 'Little Noses Decongestant Nose Drops', 'Phenylephrine Hydrochloride', 'Medtech Products Inc.', NULL, NULL),
	(3184, 'Avena Valeriana Nerve Relief', 'AVENA SATIVA FLOWERING TOP, VALERIAN, OSTREA EDULIS SHELL, PHOSPHORUS, SULFUR', 'Uriel Pharmacy Inc', NULL, NULL),
	(3194, 'Guanfacine', 'Guanfacine', 'Carilion Materials Management', NULL, NULL),
	(3204, 'Epinephrine', 'Epinephrine', 'International Medication Systems, Limited', NULL, NULL),
	(3214, 'ESSENTIAL SOLUTION COENZYME Q10 MASK SHEET', 'GLYCERIN, ALLANTOIN', 'NATURE REPUBLIC CO., LTD.', NULL, NULL),
	(3224, 'bareMinerals', 'Titanium Dioxide and Zinc Oxide', 'Bare Escentuals Beauty Inc.', NULL, NULL),
	(3234, 'Tranylcypromine Sulfate', 'tranylcypromine sulfate', 'REMEDYREPACK INC.', NULL, NULL),
	(3244, 'Valacyclovir Hydrochloride', 'Valacyclovir Hydrochloride', 'Bryant Ranch Prepack', NULL, NULL),
	(3254, 'Primidone', 'Primidone', 'Dr. Reddy\'s Laboratories Ltd', NULL, NULL),
	(3264, 'N - TIME', 'ACETAMINOPHEN, DOXYLAMINE SUCCINATE, and DEXTROMETHORPHAN HYDROBROMIDE', 'SPIRIT PHARMACEUTICALS,LLC', NULL, NULL),
	(3284, 'Greasewood', 'Greasewood', 'Nelco Laboratories, Inc.', NULL, NULL),
	(3294, 'Lyrica', 'PREGABALIN', 'Parke-Davis Div of Pfizer Inc', NULL, NULL),
	(3304, 'Viva CT', 'FOLIC ACID, FERROUS FUMARATE, ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, THIAMINE MONONITRATE, RIBOFLAVIN, PYRIDOXINE HYDROCHLORIDE, CYANOCOBALAMIN, ZINC OXIDE, CUPRIC SULFATE ANHYDROUS, and Selenomethionine', 'JayMac Pharmaceuticals LLC', NULL, NULL),
	(3314, 'Ulta', 'Avobenzone, Homosalate, Octisalate, Octocrylene and Oxybenzone', 'Prime Packaging, Inc.', NULL, NULL),
	(3334, 'Imipenem and Cilastatin', 'IMIPENEM and CILASTATIN SODIUM', 'Hospira, Inc.', NULL, NULL),
	(3354, 'Nystatin', 'Nystatin', 'Cardinal Health', NULL, NULL),
	(3374, 'Vida Mia Pain Relief', 'Aspirin, Citric Acid Monohydrate, and Sodium Bicarbonate', 'Navarro Discount Pharmacies, LLC', NULL, NULL),
	(3384, 'PRAVASTATIN SODIUM', 'PRAVASTATIN SODIUM', 'Clinical Solutions Wholesale', NULL, NULL),
	(3394, 'Cymbalta', 'Duloxetine hydrochloride', 'Unit Dose Services', NULL, NULL),
	(3414, 'Nostalgia', 'Aurum metallicum, Berberis aquifolium, Calcarea carbonica, Capsicum annuum, Carbo animalis, Eupatorium purpureum, Geranium maculatum, Helleborus niger, Juglans regia, flos, Lobelia cardinalis, Lonicera caprifolium, flos, Mancinella, Melilotus officinalis,', 'King Bio Inc.', NULL, NULL),
	(3424, 'Chlorthalidone', 'chlorthalidone', 'Mylan Institutional Inc.', NULL, NULL),
	(3434, 'Potassium Chloride in Dextrose', 'Potassium Chloride and Dextrose Monohydrate', 'Baxter Healthcare Corporation', NULL, NULL),
	(3454, 'SudoGest', 'Pseudoephedrine Hydrochloride', 'Rebel Distributors Corp', NULL, NULL),
	(3464, 'Parasite Detox', 'Filix mas, Granatum, Juglans regia, Rhamnus purshiana, Absinthium, Aesculus hippocastanum, Arsenicum album, Baptisia tinctoria,', 'Apotheca Company', NULL, NULL),
	(3474, 'healthy accents naproxen sodium', 'Naproxen Sodium', 'DZA Brands LLC', NULL, NULL),
	(3484, 'Haloperidol', 'Haloperidol', 'Dispensing Solutions, Inc.', NULL, NULL),
	(3494, 'Multi-Active Day Early Wrinkle Correcting SPF 15', 'OCTINOXATE, OCTISALATE, AVOBENZONE, OCTOCRYLENE', 'Laboratoires Clarins S.A.', NULL, NULL),
	(3504, 'Prednicarbate', 'Prednicarbate', 'Prasco Laboratories', NULL, NULL),
	(3514, 'Chlorpromazine Hydrochloride', 'Chlorpromazine Hydrochloride', 'REMEDYREPACK INC.', NULL, NULL),
	(3524, 'Captopril', 'captopril', 'Mylan Institutional Inc.', NULL, NULL),
	(3534, 'Quetiapine fumarate', 'Quetiapine fumarate', 'Cardinal Health', NULL, NULL),
	(3564, 'Ranitidine Hydrochloride', 'Ranitidine Hydrochloride', 'Bryant Ranch Prepack', NULL, NULL),
	(3574, 'CLINIMIX E', 'Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Sodium Acetate, Dibasic Potassium Phosphate, Ma', 'Baxter Healthcare Corporation', NULL, NULL),
	(3584, 'Treatment Set TS340987', 'Treatment Set TS340987', 'Antigen Laboratories, Inc.', NULL, NULL),
	(3604, 'Cold-EEZE', 'Zinc Gluconate', 'ProPhase Labs, Inc.', NULL, NULL),
	(3614, 'Coconut', 'Coconut', 'Antigen Laboratories, Inc.', NULL, NULL),
	(3624, 'Tamsulosin Hydrochloride', 'tamsulosin hydrochloride', 'Mylan Institutional Inc.', NULL, NULL),
	(3634, 'Carbon Dioxide Air Mix', 'Carbon Dioxide Air Mix', 'Medical-Technical Gases, Inc.', NULL, NULL),
	(3654, 'Carbo Chamomilla Digestive Support', 'ACTIVATED CHARCOAL ARTEMISIA ABSINTHIUM FLOWERING TOP MATRICARIA RECUTITA GENTIANA LUTEA ROOT AVENS EXTRACT BLACK PEPPER GINGER ANTIMONY TRISULFIDE ARSENIC TRIOXIDE', 'Uriel Pharmacy Inc', NULL, NULL),
	(3674, 'Quiet Calm', 'Quiet Calm', 'Apotheca Company', NULL, NULL),
	(3694, 'AZITHROMYCIN', 'AZITHROMYCIN', 'American Health Packaging', NULL, NULL),
	(3704, 'Fenofibric Acid', 'Fenofibric Acid', 'Zydus Pharmaceuticals USA Inc', NULL, NULL),
	(3714, 'Triple Antibiotic', 'bacitracin zinc, neomycin sulfate, polymyxin b sulfate', 'Moore Medical LLC', NULL, NULL),
	(3734, 'Micardis HCT', 'TELMISARTAN AND HYDROCHLOROTHIAZIDE', 'Physicians Total Care, Inc.', NULL, NULL),
	(3744, 'ENALAPRIL MALEATE AND HYDROCHLOROTHIAZIDE', 'ENALAPRIL MALEATE AND HYDROCHLOROTHIAZIDE', 'Physicians Total Care, Inc.', NULL, NULL),
	(3754, 'Nevirapine', 'Nevirapine', 'Apotex Corp', NULL, NULL),
	(3774, 'Diphenoxylate Hydrochloride and Atropine Sulfate', 'Diphenoxylate Hydrochloride and Atropine Sulfate', 'Par Pharmaceutical, Inc.', NULL, NULL),
	(3794, 'Piroxicam', 'Piroxicam', 'H.J. Harkins Company, Inc.', NULL, NULL),
	(3804, 'Guaifenesin', 'Guaifenesin', 'Physicians Total Care, Inc.', NULL, NULL),
	(3814, 'Licenex', 'Agaricus musc, Bovista, Muriaticum Ac, Pix liquida, Staphysag, Sulphur, Anacardium or, Apis mel, Causticum, Graphites, Oleander, Quassia, Rhus tox', 'Ionx Holdings d/b/a HelloLife Inc.', NULL, NULL),
	(3834, 'Hydroxyzine HCl', 'Hydroxyzine HCl', 'STI Pharma LLC', NULL, NULL),
	(3844, 'CAREONE', 'Bacitracin Zinc, Neomycin Sulfate, and Polymyxin B Sulfate', 'American Sales Company', NULL, NULL),
	(3864, 'Carisoprodol', 'Carisoprodol', 'West-ward Pharmaceutical Corp', NULL, NULL),
	(3884, 'Phoenix Balm', 'Pain Relief Rub', 'Amazonian Naturals, Inc.', NULL, NULL),
	(3894, 'Quartz Oxalis Nicotiana', 'Quartz Oxalis Nicotiana', 'Uriel Pharmacy Inc.', NULL, NULL),
	(3904, 'SALSALATE', 'SALSALATE', 'Libertas Pharma, Inc.', NULL, NULL),
	(3914, 'Prednisolone Sodium Phosphate', 'Prednisolone Sodium Phosphate', 'Physicians Total Care, Inc.', NULL, NULL),
	(3934, 'Hog Hair', 'Hog Hair', 'Antigen Laboratories, Inc.', NULL, NULL),
	(3944, 'ATORVASTATIN CALCIUM', 'ATORVASTATIN CALCIUM', 'American Health Packaging', NULL, NULL),
	(3954, 'Lab1796 Sinus Appeaser', 'Asafetida, Echinacea angustifolia, Calcium sulfide, Potassium dichromate, Luffa operculata fruit, Silicon dioxide, Sinusitisinum', 'HomeopathyStore.com', NULL, NULL),
	(3994, 'Insects (whole body) cockroach mix', 'Insects (whole body) cockroach mix', 'Jubilant HollisterStier LLC', NULL, NULL),
	(4004, 'Extended Phenytoin Sodium', 'Phenytoin Sodium', 'REMEDYREPACK INC.', NULL, NULL),
	(4014, 'Sciatic Rescue', 'Phytolacca Decandra, Gnaphalium Polycephalum, Colocynthis, Gelsemium Sempervirens', 'Peaceful Mountain, Inc.', NULL, NULL),
	(4024, 'Clonazepam', 'Clonazepam', 'Golden State Medical Supply, Inc', NULL, NULL),
	(4034, 'Treatment Set TS332080', 'Treatment Set TS332080', 'Antigen Laboratories, Inc.', NULL, NULL),
	(4044, 'KETOROLAC TROMETHAMINE', 'KETOROLAC TROMETHAMINE', 'REMEDYREPACK INC.', NULL, NULL),
	(4064, 'Dilaudid', 'hydromorphone hydrochloride', 'Purdue Pharma LP', NULL, NULL),
	(4084, 'Fosinopril Sodium', 'Fosinopril Sodium', 'Teva Pharmaceuticals USA Inc', NULL, NULL),
	(4104, 'Olanzapine', 'Olanzapine', 'Prasco Laboratories', NULL, NULL),
	(4144, 'Bisacodyl', 'Bisacodyl', 'Cardinal Health', NULL, NULL),
	(4154, 'Zyvox', 'linezolid', 'Pharmacia and Upjohn Company', NULL, NULL),
	(4194, 'CV', 'Lycopus virginicus, Valeriana officinalis, Aurum metallicum, Cactus grandiflorus, Cuprum aceticum,', 'Apotheca Company', NULL, NULL),
	(4204, 'Sabina Kit Refill', 'JUNIPERUS SABINA LEAF', 'Washington Homeopathic Products', NULL, NULL),
	(4214, 'Alka-Seltzer Plus Cold Medicine Sparkling Original', 'ASPIRIN, CHLORPHENIRAMINE MALEATE, and PHENYLEPHRINE BITARTRATE', 'Bayer HealthCare Consumer Care', NULL, NULL),
	(4224, 'Lisinopril and Hydrochlorothiazide', 'Lisinopril and hydrochlorothiazide', 'Ranbaxy Pharmaceuticals Inc.', NULL, NULL),
	(4234, 'Benzoin Tincture', 'Benzoin Resin', 'Humco Holding Group, Inc.', NULL, NULL),
	(4244, 'ULTRAM', 'tramadol hydrochloride', 'PD-Rx Pharmaceuticals, Inc.', NULL, NULL),
	(4254, 'Cefuroxime', 'cefuroxime sodium', 'Sagent Pharmaceuticals', NULL, NULL),
	(4264, 'DOCEFREZ', 'docetaxel anhydrous', 'Sun Pharma Global FZE', NULL, NULL),
	(4274, 'Acremonium strictum', 'Acremonium strictum', 'Nelco Laboratories, Inc.', NULL, NULL),
	(4284, 'UTI and Kidney Stones', 'Apis, Berberis Vulgaris, Bryonia, Cantharis, Staphysaria, Sarsaparilla, Urtica Urens', 'Home Sweet Homeopathics', NULL, NULL),
	(4294, 'Citalopram', 'Citalopram', 'Amneal Pharmaceuticals of New York, LLC', NULL, NULL),
	(4304, 'CD HydraLife BB Creme Enhancing Sunscreen Moisturizer For Immediate Beauty Golden Peach Broad Spectrum SPF 30', 'OCTINOXATE, OXYBENZONE, TITANIUM DIOXIDE', 'Parfums Christian Dior', NULL, NULL),
	(4314, 'Burns', 'Arnica, Cantharis, Calendula, Causticum, Hypericum, Urtica Urens', 'Home Sweet Homeopathics', NULL, NULL),
	(4334, 'ACD-A', 'Antiocoagulant Citrate Dextrose Solution, Formula A', 'Fenwal Inc.', NULL, NULL),
	(4344, 'PAMO Kill Natural', 'GINKGO BILOBA LEAF OIL', 'GeoRim Pharmaceutical', NULL, NULL),
	(4364, 'Candida albicans', 'Candida albicans', 'Nelco Laboratories, Inc.', NULL, NULL),
	(4384, 'LACTULOSE', 'LACTULOSE', 'Cardinal Health', NULL, NULL),
	(4394, 'Diuretic', 'Apis Melifica, Berberis vulgaris, Nelleborus niger, Juniperus communis, Prunus spinosa, Strophanthus hispidus, Taraxacum offidcinale, Uva-Ursi,', 'Liddell Laboratories, Inc.', NULL, NULL),
	(4414, 'up and up antibiotic', 'bacitracin, neomycin, polymyxin B', 'Target Corporation', NULL, NULL),
	(4444, 'Promethazine Hydrochloride', 'Promethazine Hydrochloride', 'West-ward Pharmaceutical Corp.', NULL, NULL),
	(4484, 'prenate essential', '- ascorbic acid, cholecalciferol, .alpha.-tocopherol, dl-, pyridoxine hydrochloride, folic acid, cyanocobalamin, biotin, calcium carbonate, ferrous fumarate, potassium iodide, magnesium oxide, doconexent and icosapent', 'Avion Pharmaceuticals, LLC', NULL, NULL),
	(4504, 'Nitrogen', 'Nitrogen', 'Andy-Oxy Co., Inc.', NULL, NULL),
	(4514, 'Gumsol', 'Benzocaine, Zinc Chloride', 'Kramer Novis', NULL, NULL),
	(4534, 'IPKN ARTISTS TOUCH BB 01 LIGHT', 'TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', 'Inel Cosmetics Co., Ltd.', NULL, NULL),
	(4544, 'lice treatment', 'Permethrin', 'Walgreen Company', NULL, NULL),
	(4574, 'Givenchy Photo Perfexion Fluid Foundation Broad Spectrum SPF 20 Perfect Beige', 'TITANIUM DIOXIDE, OCTINOXATE', 'LVMH Fragrance Brands', NULL, NULL),
	(4584, 'Alba Lip Care Sunblock SPF 25', 'Octocrylene, Ethylhexyl Methoxycinnamate, Zinc Oxide, Ethylhexyl Salicilate', 'The Hain Celestial Group, Inc.', NULL, NULL),
	(4594, 'Formo Cresol', 'Cresol', 'DSHealthcare', NULL, NULL),
	(4614, 'ConRx AR', 'ALUMINUM HYDROXIDE and MAGNESIUM HYDROXIDE', 'Eagle Distributors,Inc.', NULL, NULL),
	(4634, 'Moxifloxacin', 'Moxifloxacin', 'Dr. Reddy\'s Laboratories Limited', NULL, NULL),
	(4644, 'Desmopressin Acetate', 'Desmopressin Acetate', 'American Health Packaging', NULL, NULL),
	(4654, 'AMBROSIA PSILOSTACHYA POLLEN', 'Ragweed Western', 'ALK-Abello, Inc.', NULL, NULL),
	(4684, 'Procardia', 'nifedipine', 'Pfizer Laboratories Div Pfizer Inc', NULL, NULL),
	(4694, 'Air, Compressed', 'Nitrogen, Oxygen', 'Linde Gas North America LLC', NULL, NULL),
	(4704, 'E-Z-Paste', 'Barium Sulfate', 'E-Z-EM Canada Inc', NULL, NULL),
	(4714, 'HOLCUS LANATUS POLLEN', 'Velvet Grass', 'ALK-Abello, Inc.', NULL, NULL),
	(4724, 'Bald Cypress', 'Bald Cypress', 'Nelco Laboratories, Inc.', NULL, NULL),
	(4734, 'Dior Bronze Collagen Activ SPF 15 002', 'OXYBENZONE, OCTINOXATE, TITANIUM DIOXIDE', 'Parfums Christian Dior', NULL, NULL),
	(4744, 'Potassium Chloride', 'Potassium Chloride', 'Sandoz Inc', NULL, NULL),
	(4774, 'Myxcin-C', 'Hexylresorcinol', 'Phoenix Global Supply Group, Inc.', NULL, NULL),
	(4784, 'NANO PPC', 'NANO PPC', 'YBK Investment, INC', NULL, NULL),
	(4794, 'Rest Simply', 'Diphenhydramine HCl', 'NASH-FINCH COMPANY', NULL, NULL),
	(4804, 'Mango Blossom', 'Mango Blossom', 'Nelco Laboratories, Inc.', NULL, NULL),
	(4824, 'Non-Drowsy DayTime Cold and Flu Multi-Symptom Relief', 'ACETAMINOPHEN, PHENYLEPHRINE HCL, DEXTROMETHORPHAN HBr', 'Robinson Pharma, Inc.', NULL, NULL),
	(4834, 'Aveeno Positively Radiant CC', 'Homosalate, Octinoxate, Octisalate, and Oxybenzone', 'Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', NULL, NULL),
	(4844, 'Trandolapril and Verapamil Hydrochloride', 'Trandolapril and Verapamil Hydrochloride', 'Glenmark Generics Inc., USA', NULL, NULL),
	(4864, 'Pindolol', 'pindolol', 'Carilion Materials Management', NULL, NULL),
	(4874, 'Tafinlar', 'dabrafenib', 'GlaxoSmithKline LLC', NULL, NULL),
	(4884, 'Acyclovir', 'Acyclovir', 'Bryant Ranch Prepack', NULL, NULL),
	(4894, 'Eastern Cottonwood', 'Eastern Cottonwood', 'Nelco Laboratories, Inc.', NULL, NULL),
	(4904, 'Kleenex Antiseptic Skin Cleanser', 'Chloroxylenol', 'Kimberly-Clark Corporation', NULL, NULL),
	(4914, 'Cranberry', 'Cranberry', 'Antigen Laboratories, Inc.', NULL, NULL),
	(4934, 'Bacitracin Zinc', 'bacitracin zinc', 'A-S Medication Solutions LLC', NULL, NULL),
	(4944, 'Saline Laxative', 'sodium phosphate', 'Safeway', NULL, NULL),
	(4964, 'Cough and Bronchial with Zinc', 'ANTIMONY PENTASULFIDE, BRYONIA ALBA ROOT, DROSERA ROTUNDIFOLIA, EUCALYPTUS GLOBULUS LEAF, IPECAC, SPONGIA OFFICINALIS SKELETON, ROASTED, ZINC GLUCONATE', 'Nature\'s Way Products, Inc.', NULL, NULL),
	(4984, 'Lucky Supersoft', 'Menthol Zinc Oxide', 'Delta Brands Inc', NULL, NULL),
	(4994, 'Chlorothiazide', 'Chlorothiazide', 'West-ward Pharmaceutical Corp', NULL, NULL),
	(5024, 'Homeopathic Eye Strain', 'silver nitrate, eyebright, carbonate of potassium, garden rue', 'Indiana Botanic Gardens', NULL, NULL),
	(5084, 'Apis ex animale 6 Special Order', 'Apis ex animale 6 Special Order', 'Uriel Pharmacy Inc.', NULL, NULL),
	(5104, 'JUNIPERUS ASHEI POLLEN', 'Mountain Cedar', 'ALK-Abello, Inc.', NULL, NULL),
	(5114, 'CVTox', 'Cochlearia armoracia, Echinacea, Hydrastis canadensis, Lomatium dissectum, Tabebuia impetiginosa, Propolis, Glandula suprarenalis bovinum, Thymus gland (suis), Aranea diadema, Ipecacuanha, Lycopodium clavatum, Muriaticum acidum, Nitricum acidum, Phosphori', 'BioActive Nutritional', NULL, NULL),
	(5124, 'MEDI-DERM TOPICAL PAIN RELIEF', 'METHYL SALICYLATE MENTHOL CAPSAICIN', 'Two Hip Consulting, LLC', NULL, NULL),
	(5134, 'Allopurinol', 'allopurinol', 'Lake Erie Medical DBA Quality Care Products LLC', NULL, NULL),
	(5144, 'Synthroid', 'Levothyroxine Sodium', 'AbbVie Inc.', NULL, NULL),
	(5184, 'Coast Maple', 'Coast Maple', 'Nelco Laboratories, Inc.', NULL, NULL),
	(5194, 'TUNA', 'Tuna', 'ALK-Abello, Inc.', NULL, NULL),
	(5204, 'CENTER-AL - ULMUS AMERICANA POLLEN', 'Allergenic Extracts Alum Precipitated', 'ALK-Abello, Inc.', NULL, NULL),
	(5214, 'Losartan Potassium', 'Losartan Potassium', 'Dispensing Solutions, Inc.', NULL, NULL),
	(5234, 'CEFTRIAXONE', 'CEFTRIAXONE', 'Wockhardt Limited', NULL, NULL),
	(5244, 'Goldenrod', 'Goldenrod', 'Nelco Laboratories, Inc.', NULL, NULL),
	(5254, 'Pulsatilla Compositum', 'PULSATILLA VULGARIS and SULFUR and CORTISONE ACETATE', 'Heel Inc', NULL, NULL),
	(5274, 'Nyloxin', 'NAJA NAJA VENOM', 'Receptopharm Inc.', NULL, NULL),
	(5284, 'Tandem - F', 'Ferrous Fumarate and Polysacchride Iron Complex and Folic Acid', 'US Pharmaceutical Corporation', NULL, NULL),
	(5294, 'Pollens - Trees, Walnut, Black Juglans nigra', 'Walnut, Black Juglans nigra', 'Jubilant HollisterStier LLC', NULL, NULL),
	(5304, 'Enviro', 'Kali gluconicum, Glandula suprarenalis suis, Hepar suis, Arsenicum album, Iridium metallicum, Phosphorus, Selenium metallicum, Sulphur, Histaminum hydrochloricum, Hyaluronidase, Interferon, Serotonin,', 'Deseret Biologicals, Inc.', NULL, NULL),
	(5314, 'Irbesartan', 'Irbesartan', 'Aurobindo Pharma Limited', NULL, NULL),
	(5324, 'Luxiq', 'Betamethasone Valerate', 'Prestium Pharma, Inc.', NULL, NULL),
	(5334, 'RITEAID HEMORRHOIDAL COOLING', 'WITCH HAZEL, PHENYLEPHRINE HYDROCHLORIDE', 'Rite Aid Corporation', NULL, NULL),
	(5344, 'PCXX ONE MINTE GEL CREME DE MENTHE', 'FLUORIDE TREATMENT', 'Ross Healthcare Inc.', NULL, NULL),
	(5364, 'Venoforce', 'Aesculus Hippocastanum, Collinsonia Canadensis, Echinacea, Hamamelis Virginiana, Pulsatilla, Arnica Montana', 'BioActive Nutritional, Inc.', NULL, NULL),
	(5374, 'Stachybotrys', 'Stachybotrys', 'Antigen Laboratories, Inc.', NULL, NULL),
	(5384, 'Cepacol', 'Benzocaine and Dextromethorphan Hydrobromide', 'Reckitt Benckiser LLC', NULL, NULL),
	(5414, 'Sore Throat', 'BARIUM CATION', 'Natural Health Supply', NULL, NULL),
	(5424, 'Ergocalciferol', 'ergocalciferol', 'Winthrop U.S.', NULL, NULL),
	(5444, 'Feather Mixture', 'Feather Mixture', 'Antigen Laboratories, Inc.', NULL, NULL),
	(5454, 'GAMMAGARD S/D', 'HUMAN IMMUNOGLOBULIN G', 'Baxter Healthcare Corporation', NULL, NULL),
	(5464, 'Glyburide (micronized) and Metformin Hydrochloride', 'Glyburide (micronized) and Metformin Hydrochloride', 'Actavis Pharma Manufacturing Pvt. Ltd.', NULL, NULL),
	(5474, 'Trihexyphenidyl Hydrochloride', 'trihexyphenidyl hydrochloride', 'Clinical Solutions Wholesale', NULL, NULL),
	(5494, 'Motion Sickness', 'Dimenhydrinate', 'Good Sense (Geiss, Destin & Dunn, Inc.)', NULL, NULL),
	(5534, 'Professional Therapy', 'Diabetic Pain Relieving', 'Active and Innovative', NULL, NULL),
	(5554, 'Lactic Acid', 'Lactic Acid', 'Stratus Pharamceuticals, Inc', NULL, NULL),
	(5584, 'Desoximetasone', 'Desoximetasone', 'E. Fougera & Co., a division of Fougera Pharmaceuticals Inc.', NULL, NULL),
	(5604, 'Zenzedi', 'Dextroamphetamine Sulfate', 'Arbor Pharmaceuticals, Inc.', NULL, NULL),
	(5624, 'Brome Grass', 'Brome Grass', 'Nelco Laboratories, Inc.', NULL, NULL),
	(5634, 'Oxaliplatin', 'Oxaliplatin', 'Pfizer Laboratories Div Pfizer Inc.', NULL, NULL),
	(5644, 'Sertraline Hydrochloride', 'Sertraline Hydrochloride', 'Aurolife Pharma LLC', NULL, NULL),
	(5654, 'MICRONOR', 'norethindrone', 'Physicians Total Care, Inc.', NULL, NULL),
	(5664, 'CareOne Allergy Relief', 'Loratadine', 'American Sales Company', NULL, NULL),
	(5674, 'ConRx', 'Acetaminophen, Chlorpheniramine maleate, and Phenylephrine Hydrochloride', 'Eagle Distributors,Inc.', NULL, NULL),
	(5694, 'Pollens - Trees, Cottonwood, Common Populus deltoides', 'Cottonwood, Common Populus deltoides', 'Jubilant HollisterStier LLC', NULL, NULL),
	(5704, 'Prostoforce', 'Aralia quinquefolia, Damiana, Hydrocotyle asiatica, Juniperus virginiana, Pareira brava, Sabal serrulata, Thuja occidentalis, Clematis erecta, Conium maculatum, Pulsatilla,', 'Apotheca Company', NULL, NULL),
	(5734, 'Zovia 1/50E-28', 'Ethynodiol Diacetate and Ethinyl Estradiol', 'Watson Pharma, Inc.', NULL, NULL),
	(5744, 'Glyburide-Metformin Hydrochloride', 'Glyburide-Metformin Hydrochloride', 'Heritage Pharmaceuticals Inc.', NULL, NULL),
	(5764, 'Systane', 'polyethylene glycol 0.4% and propylene glycol 0.3%', 'Alcon Research Ltd', NULL, NULL),
	(5794, 'Terbutaline Sulfate', 'Terbutaline Sulfate', 'Rebel Distributors Corp', NULL, NULL),
	(5814, 'ARNICA', 'ARNICA MONTANA', 'Hyland\'s', NULL, NULL),
	(5824, 'SUPER DEFENSE', 'OXYBENZONE, OCTISALATE, AVOBENZONE', 'CLINIQUE LABORATORIES INC', NULL, NULL),
	(5834, 'Metolazone', 'Metolazone', 'NCS HealthCare of KY, Inc dba Vangard Labs', NULL, NULL),
	(5844, 'Perindopril Erbumine', 'Perindopril Erbumine', 'Aurobindo Pharma Limited', NULL, NULL),
	(5854, 'Mitomycin', 'Mitomycin', 'Accord Healthcare Inc', NULL, NULL),
	(5904, 'Black Willow', 'Black Willow', 'Nelco Laboratories, Inc.', NULL, NULL),
	(5914, 'Sulwhasoo Lumitouch Foundation', 'OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE', 'AMOREPACIFIC', NULL, NULL),
	(5934, 'Desipramine Hydrochloride', 'Desipramine Hydrochloride', 'Preferred Pharmaceuticals, Inc', NULL, NULL),
	(5974, 'Your Logo Here Burn First Aid', 'benzocaine, benzethonium chloride, and menthol', 'Dixon Investments, Inc.', NULL, NULL),
	(6024, 'RespiratoryCare', 'Ammonium carbonicum, Antimonium tartaricum, Carbo vegetabilis, Chlorinum, Kali carbonicum, Lobelia inflata, Phosphorus, Silicea, and Stannum metallicum', 'King Bio Inc', NULL, NULL),
	(6034, 'Hot Spot', 'capsaicin', 'fabrication enterprises', NULL, NULL),
	(6044, 'Cyproheptadine Hydrochloride', 'Cyproheptadine Hydrochloride', 'NCS HealthCare of KY, Inc dba Vangard Labs', NULL, NULL),
	(6064, 'Keflex', 'cephalexin', 'Shionogi Inc.', NULL, NULL),
	(6094, 'Benzonatate', 'Benzonatate', 'Rebel Distributors Corp', NULL, NULL),
	(6104, 'Digoxin', 'Digoxin', 'American Health Packaging', NULL, NULL),
	(6124, 'Clindamycin', 'Clindamycin Phosphate', 'Akorn, Inc.', NULL, NULL),
	(6134, 'Trazodone Hydrochloride', 'Trazodone Hydrochloride', 'Qualitest Pharmaceuticals', NULL, NULL),
	(6144, 'Imipramine Hydrochloride', 'Imipramine Hydrochloride', 'Par Pharmaceutical Inc.', NULL, NULL),
	(6154, 'SUPRAX', 'cefixime', 'LUPIN LIMITED', NULL, NULL),
	(6164, 'Body Scrub', 'Glycerin and Kaolin', 'Milk & Co Pty Ltd', NULL, NULL),
	(6194, 'Cough with 100% Natural Honey 4 Kids', 'IPECAC, ACONITUM NAPELLUS, SPONGIA OFFICINALIS SKELETON, ROASTED, and ANTIMONY POTASSIUM TARTRATE', 'Hylands Inc.', NULL, NULL),
	(6214, 'Naropin', 'ROPIVACAINE HYDROCHLORIDE', 'Fresenius Kabi USA, LLC', NULL, NULL),
	(6244, 'NATRUM MURIATICUM', 'NATRUM MURIATICUM', 'HOMEOLAB USA INC', NULL, NULL),
	(6284, 'ibu profen cold and sinus', 'Ibuprofen, Pseudoephedrine Hydrochloride', 'Rite Aid Corporation', NULL, NULL),
	(6294, 'isosorbide mononitrate', 'isosorbide mononitrate', 'Kremers Urban Pharmaceuticals Inc.', NULL, NULL),
	(6314, 'hemorrhoidal', 'Mineral oil, petrolatum, phenylephrine hcl', 'Perrigo New York Inc', NULL, NULL),
	(6374, 'ARMOUR THYROID', 'THYROID', 'Rebel Distributors Corp', NULL, NULL),
	(6384, 'Progesterone', 'Progesterone,', 'Apotheca Company', NULL, NULL),
	(6444, 'Procainamide Hydrochloride', 'PROCAINAMIDE HYDROCHLORIDE', 'Hospira, Inc.', NULL, NULL),
	(6454, 'Terbinafine Hydrochloride', 'Terbinafine Hydrochloride', 'Cardinal Health', NULL, NULL),
	(6504, 'California Black Walnut', 'California Black Walnut', 'Nelco Laboratories, Inc.', NULL, NULL),
	(6524, 'Losartan Potassium and Hydrochlorothiazide', 'Losartan Potassium and Hydrochlorothiazide', 'Torrent Pharmaceuticals Limited', NULL, NULL),
	(6544, 'COCHLIOBOLUS SATIVUS', 'HELMINTHOSPORIUM SOROKINIANUM', 'ALK-Abello, Inc.', NULL, NULL),
	(6554, 'Orphenadrine Citrate', 'Orphenadrine Citrate', 'PD-Rx Pharmaceuticals, Inc.', NULL, NULL),
	(6574, 'Chestnut', 'Chestnut', 'Nelco Laboratories, Inc.', NULL, NULL),
	(6584, 'Kroger Sunscreen', 'OCTINOXATE OXYBENZONE', 'THE KROGER CO', NULL, NULL),
	(6604, 'Spironolactone', 'spironolactone', 'NCS HealthCare of KY, Inc dba Vangard Labs', NULL, NULL),
	(6614, 'ORIGINAL HEALING', 'PINE NEEDLE OIL (PINUS SYLVESTRIS) SAMBUCUS NIGRA FLOWER CALENDULA OFFICINALIS FLOWER ECHINACEA ANGUSTIFOLIA', 'PUREMEDY', NULL, NULL),
	(6624, 'Food - Plant Source, Peach Prunus persica', 'Peach Prunus persica', 'Jubilant HollisterStier LLC', NULL, NULL),
	(6634, 'Bromfed', 'Brompheniramine Maleate, Pseudoephedrine Hydrochloride and Dextromethorphan Hydrobromide', 'Morton Grove Pharmaceuticals, Inc.', NULL, NULL),
	(6644, 'CLE DE PEAU BEAUTE GENTLE PROTECTIVE I', 'AVOBENZONE, OCTINOXATE, OCTOCRYLENE, and OXYBENZONE', 'SHISEIDO CO., LTD.', NULL, NULL),
	(6654, 'Erythromycin', 'erythromycin', 'Physicians Total Care, Inc.', NULL, NULL),
	(6664, 'IFEX', 'ifosfamide', 'Baxter Healthcare Corporation', NULL, NULL),
	(6684, 'Methimazole', 'Methimazole', 'REMEDYREPACK INC.', NULL, NULL),
	(6704, 'COUGH AND COLD NIGHTTIME FORMULA KIDS RELIEF', 'DROSERA, ARNICA MONTANA, BRYONIA, CETRARIA ISLANDICA, BELLADONNA, COCCUS CACTI, STANNUM METALLICUM, CHAMOMILLA, COFFEA CRUDA', 'HOMEOLAB USA INC', NULL, NULL),
	(6734, 'Hemorrhoid Care', 'Hamamelis virginiana, Aesculus hippocastanum, Aloe socotrina, Paeonia officinalis, Ignatia amara, Lycopodium clavatum, Nitricum acidum, Nux vomica, Phosphorus, Podophyllum peltatum, Pulsatilla, Sulphu', 'Apotheca Company', NULL, NULL),
	(6754, 'Ferrum silicicum Urtica', 'Ferrum silicicum Urtica', 'Uriel Pharmacy Inc.', NULL, NULL),
	(6774, 'Felbamate', 'Felbamate', 'Amneal Pharmaceuticals', NULL, NULL),
	(6804, 'BETULA LENTA POLLEN', 'Black Birch', 'ALK-Abello, Inc.', NULL, NULL),
	(6824, 'Helium Oxygen', 'Helium Oxygen', 'Airgas National Welders', NULL, NULL),
	(6834, 'TOPIRAMATE', 'TOPIRAMATE', 'Dispensing Solutions, Inc.', NULL, NULL),
	(6844, 'Benazepril Hydrochloride', 'Benazepril Hydrochloride', 'Unit Dose Services', NULL, NULL),
	(6854, 'Amlodipine Besylate and Benazepril Hydrochloride', 'amlodipine besylate and benazepril hydrochloride', 'Lake Erie Medical DBA Quality Care Products LLC', NULL, NULL),
	(6874, 'Pollens - Trees, Maple, Hard Acer saccharum', 'Maple, Hard Acer saccharum', 'Jubilant HollisterStier LLC', NULL, NULL),
	(6894, 'equaline enema', 'Saline', 'Supervalu Inc', NULL, NULL),
	(6914, 'Quinapril', 'Quinapril', 'Lupin Pharmaceuticals, Inc.', NULL, NULL),
	(6924, 'Bethanechol Chloride', 'BETHANECHOL CHLORIDE', 'Global Pharmaceuticals, Division of Impax Laboratories, Inc.', NULL, NULL),
	(6934, 'Rescue Remedy Kids', 'HELIANTHEMUM NUMMULARIUM FLOWER, CLEMATIS VITALBA FLOWER, IMPATIENS GLANDULIFERA FLOWER, PRUNUS CERASIFERA FLOWER, and ORNITHOGALUM UMBELLATUM', 'Nelson Bach USA, Ltd.', NULL, NULL),
	(6944, 'Mycophenolic Acid', 'Mycophenolic Acid', 'Apotex Corp', NULL, NULL),
	(6974, 'Denti-Care', 'Fluoride Ions', 'AR Medicom Inc', NULL, NULL),
	(6994, 'Sucralfate', 'Sucralfate', 'NCS HealthCare of KY, Inc dba Vangard Labs', NULL, NULL),
	(7004, 'Fexofenadine HCl', 'Fexofenadine HCl', 'Chain Drug Consortium, LLC (Premier Value)', NULL, NULL),
	(7024, 'Skin So Soft Firm and Restore', 'Octinoxate, Oxybenzone, Octisalate, Avobenzone', 'Avon Products, Inc.', NULL, NULL),
	(7054, 'Triamterene and Hydrochlorothiazide', 'Triamterene and Hydrochlorothiazide', 'Preferred Pharmaceuticals, Inc.', NULL, NULL),
	(7064, 'RETROVIR', 'zidovudine', 'ViiV Healthcare Company', NULL, NULL),
	(7084, 'ageLOC Transformation', 'Avobenzone, Homosalate, Octisalate, and Octocrylene', 'NSE Products, Inc.', NULL, NULL),
	(7104, 'Bromday', 'bromfenac', 'Ista Pharmaceuticals, Inc', NULL, NULL),
	(7114, 'BEAUTE INITIALE', 'ENERGIZING MULTI-PROTECTION CREAM', 'CHANEL PARFUMS BEAUTE', NULL, NULL),
	(7134, 'FAGUS GRANDIFOLIA POLLEN', 'Beech', 'ALK-Abello, Inc.', NULL, NULL),
	(7144, 'Amitriptyline Hydrochloride', 'Amitriptyline Hydrochloride', 'Dispensing Solutions, Inc.', NULL, NULL),
	(7194, 'Teething', 'TRIBASIC CALCIUM PHOSPHATE, MATRICARIA RECUTITA, ARABICA COFFEE BEAN, and ATROPA BELLADONNA', 'Hyland\'s', NULL, NULL),
	(7214, 'healthy accents maldroxal', 'Aluminum hydroxide, Magnesium hydroxide, Simethicone', 'DZA Brands LLC', NULL, NULL),
	(7224, 'Advanced Eye Relief/ Redness Maximum Relief', 'Naphazoline Hydrochloride and Hypromellose', 'Bausch & Lomb Incorporated', NULL, NULL),
	(7254, 'DIORSNOW UV SHIELD BB CREME WHITE REVEAL UV PROTECTION SPF 50', 'OCTINOXATE, TITANIUM DIOXIDE, OXYBENZONE', 'Parfums Christian Dior', NULL, NULL),
	(7294, 'Emtriva', 'emtricitabine', 'State of Florida DOH Central Pharmacy', NULL, NULL),
	(7304, 'ADVAIR DISKUS', 'fluticasone propionate and salmeterol', 'Physicians Total Care, Inc.', NULL, NULL),
	(7314, 'Glipizide and Metformin Hydrochloride', 'Glipizide and Metformin Hydrochloride', 'Teva Pharmaceuticals USA Inc', NULL, NULL),
	(7364, 'EPOGEN', 'epoetin alfa', 'Amgen Inc', NULL, NULL),
	(7374, 'SH18', 'HYDROQUINONE', 'International Beauty Exchange', NULL, NULL),
	(7404, 'Morphine Sulfate', 'Morphine Sulfate', 'PD-Rx Pharmaceuticals, Inc.', NULL, NULL),
	(7424, 'Traumeel X', 'CALENDULA OFFICINALIS FLOWERING TOP and HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK and ARNICA MONTANA ROOT and ACONITUM NAPELLUS and ATROPA BELLADONNA and BELLIS PERENNIS and MATRICARIA RECUTITA and ECHINACEA, UNSPECIFIED and ECHINACEA PURPUREA and ACHILLEA', 'Biologische Heilmittel Heel', NULL, NULL),
	(7444, 'Atovaquone and Proguanil Hydrochloride', 'Atovaquone and Proguanil Hydrochloride', 'Dispensing Solutions, Inc.', NULL, NULL),
	(7454, 'Actidose Aqua', 'activated charcoal', 'Paddock Laboratories, LLC', NULL, NULL),
	(7474, 'HYDROCODONE BITARTRATE', 'HYDROCODONE BITARTRATE', 'DIRECT RX', NULL, NULL),
	(7484, 'Good Sense Nasal', 'oxymetazoline hydrochloride', 'L Perrigo Company', NULL, NULL),
	(7504, 'Maxipime', 'CEFEPIME HYDROCHLORIDE', 'Hospira, Inc.', NULL, NULL),
	(7514, 'Corn Grass', 'Corn Grass', 'Nelco Laboratories, Inc.', NULL, NULL),
	(7544, 'OLEA EUROPAEA POLLEN', 'Olive Pollen', 'ALK-Abello, Inc.', NULL, NULL),
	(7554, 'Molluscum Control', 'Lycopodium clavatum Spore, SODIUM CHLORIDE, and Thuja occidentalis leafy twig', 'Forces of Nature', NULL, NULL),
	(7594, 'GERI-LANTA ANTACID ANTIGAS', 'aluminum hydroxide, magnesium hydroxide, dimethicone', 'Geri-Care Pharmaceuticals, Corp', NULL, NULL),
	(7604, 'Solum Aesculus Sensitivity', 'Solum Aesculus Sensitivity', 'Uriel Pharmacy Inc.', NULL, NULL),
	(7634, 'Nystatin and Triamcinolone', 'Nystatin and Triamcinolone Acetonide', 'Rebel Distributors Corp', NULL, NULL),
	(7644, 'UMCKA THROAT', 'PELARGONIUM SIDOIDES ROOT', 'Natures Way Holding Co', NULL, NULL),
	(7654, 'Ovaplex', 'Angelica archangelica, Caulophyllum thalictroides, Dioscorea villosa, Oophorinum, Pituitary, Thyroidinum, Uterus, Zincum gluconicum, Apis mellifica,', 'Apotheca Company', NULL, NULL),
	(7774, 'ISAKNOX WHITE SYMPHONY BRIGHTENING EMULSION', 'ARBUTIN', 'LG Household and Healthcare, Inc.', NULL, NULL),
	(7794, 'Coppertone Sensitive Skin', 'Octinoxate, octisalate, and zinc oxide', 'MSD Consumer Care, Inc.', NULL, NULL),
	(7814, 'Endure 450', 'Alcohol hand sanitizer', 'Ecolab Inc.', NULL, NULL),
	(7824, 'PAIN AND FEVER KIDS RELIEF', 'ARNICA MONTANA, FERRUM PHOSPHORICUM, HYPERICUM PERFORATUM, BELLADONNA, THUJA OCCIDENTALIS, LEDUM PALUSTRE', 'HOMEOLAB USA INC', NULL, NULL),
	(7844, 'GAVILAX', 'Polyethylene Glycol 3350', 'GAVIS Pharmaceuticals, LLC', NULL, NULL),
	(7894, 'Glycopyrrolate', 'Glycopyrrolate', 'West-ward Pharmaceutical Corp.', NULL, NULL),
	(7904, 'Verapamil Hydrochloride', 'Verapamil Hydrochloride', 'State of Florida DOH Central Pharmacy', NULL, NULL),
	(7914, 'LBEL', 'Titanium Dioxide, Zinc Oxide, and Octinoxate', 'Ventura Corporation LTD.', NULL, NULL),
	(7944, 'Asparagus', 'Asparagus', 'Nelco Laboratories, Inc.', NULL, NULL),
	(7964, 'CNL8', 'Ciclopirox', 'Innocutis Holdings LLC', NULL, NULL),
	(7974, 'J-MAX', 'Guaifenesin, and Phenylephrine Hydrochloride', 'JayMac Pharmaceuticals LLC', NULL, NULL),
	(8004, 'Zaleplon', 'Zaleplon', 'Northstar Rx LLC', NULL, NULL),
	(8014, 'BETULA NIGRA POLLEN', 'Birch River Red', 'ALK-Abello, Inc.', NULL, NULL),
	(8024, 'Epidermophyton', 'Epidermophyton', 'Antigen Laboratories, Inc.', NULL, NULL),
	(8044, 'Aerospan', 'flunisolide', 'Acton Pharmaceuticals, Inc.', NULL, NULL),
	(8074, 'bacitracin zinc, neomycin sulfate and polymyxin b sulfate', 'bacitracin zinc, neomycin sulfate and polymyxin b sulfate', 'Sion Biotext Medical Ltd', NULL, NULL),
	(8104, 'Molds - Mold Mix 10', 'Molds - Mold Mix 10', 'Jubilant HollisterStier LLC', NULL, NULL),
	(8114, 'Sodium Sulfacetamide and Sulfur', 'Sodium Sulfacetamide and Sulfur', 'Acella Pharmaceuticals, LLC', NULL, NULL),
	(8124, 'LEDUM PAL', 'LEDUM PALUSTRE TWIG', 'Hyland\'s', NULL, NULL),
	(8144, 'Triamcinolone Acetonide', 'Triamcinolone Acetonide', 'Rebel Distributors Corp', NULL, NULL),
	(8164, 'Gastropanpar', 'Pancreas, Stomach, Arsenicum Album, Graphites, Lycopodium Clavatum, Nuv Vomica, Phosphorus, Syzygium Jambolanum', 'Energique, Inc.', NULL, NULL),
	(8174, 'Cough and Cold Relief HBP', 'Chlorpheniramine maleate and Dextromethorphan HBr', 'CHAIN DRUG MARKETING ASSOCIATION INC', NULL, NULL),
	(8184, 'Dextroamphetamine saccharate, amphetamine aspartate, dextroamphetamine sulfate, and amphetamine sulfate', 'Dextroamphetamine saccharate, Amphetamine aspartate, Dextroamphetamine sulfate, and Amphetamine sulfate', 'Caraco Pharmaceutical Laboratories, Ltd.', NULL, NULL),
	(8204, 'Hydrogen Peroxide', 'Hydrogen Peroxide', 'NDC, Inc.', NULL, NULL),
	(8214, 'Relief', 'witch hazel', 'H and P Industries, Inc. dba Triad Group', NULL, NULL),
	(8224, 'FINASTERIDE', 'FINASTERIDE', 'Bryant Ranch Prepack', NULL, NULL),
	(8274, 'Nigrospora sphaerica', 'Nigrospora sphaerica', 'Nelco Laboratories, Inc.', NULL, NULL),
	(8294, 'Polytrim', 'polymyxin b sulfate and trimethoprim sulfate', 'Allergan, Inc.', NULL, NULL),
	(8334, 'First Aid and Burn', 'Benzalkonium Chloride, Lidocaine Hydrochloride', 'Safetec of America, Inc.', NULL, NULL),
	(8344, 'NovoSeven', 'Coagulation Factor VIIa (Recombinant)', 'Novo Nordisk', NULL, NULL),
	(8364, 'Oxytocin', 'Oxytocin', 'Cantrell Drug Company', NULL, NULL),
	(8374, 'Lovenox', 'enoxaparin sodium', 'Cardinal Health', NULL, NULL),
	(8394, 'LEXIVA', 'fosamprenavir calcium', 'ViiV Healthcare Company', NULL, NULL),
	(8454, 'Ivy-Dry Super', 'BENZYL ALCOHOL, CAMPHOR, MENTHOL', 'Ivy-Dry, Inc.', NULL, NULL),
	(8464, 'COUGH BE GONE', 'Dextromethorphan Hydrobromide Guaifenesin', 'RFX Pharmaceutical Co., Ltd.', NULL, NULL),
	(8494, 'Adrenal Support', 'Aralia Quinquefolia, Humulus Lupulus, Adrenalinum, Cortisone Aceticum, Thyroidinum, Selenium Metallicum, Arsenicum Album', 'Deseret Biologicals, Inc.', NULL, NULL),
	(8514, 'Dry Eye Test', 'Fluorescein Sodium', 'Nomax Inc.', NULL, NULL),
	(8544, 'Divalproex Sodium', 'divalproex sodium', 'Mylan Institutional Inc.', NULL, NULL),
	(8554, 'Bromocriptine Mesylate', 'Bromocriptine Mesylate', 'American Health Packaging', NULL, NULL),
	(8564, 'Amytal Sodium', 'amobarbital sodium', 'Marathon Pharmaceuticals, LLC', NULL, NULL),
	(8574, 'Doxepin Hydrochloride', 'doxepin hydrochloride', 'Bryant Ranch Prepack', NULL, NULL),
	(8604, 'BANANA BOAT', 'AVOBENZONE, OCTOCRYLENE, OXYBENZONE', 'Energizer Personal Care LLC', NULL, NULL),
	(8644, 'levocetirizine dihydrochloride', 'Levocetirizine dihydrochloride', 'Perrigo New York Inc', NULL, NULL),
	(8654, 'Ablavar', 'Gadofosveset trisodium', 'Lantheus Medical Imaging, Inc.', NULL, NULL),
	(8664, 'Bio Scleranthus', 'Scleranthus Annuus, Flos', 'BioActive Nutritional, Inc.', NULL, NULL),
	(8684, 'Indapamide', 'Indapamide', 'Carilion Materials Management', NULL, NULL),
	(8694, 'Cefadroxil', 'Cefadroxil', 'Citron Pharma LLC', NULL, NULL),
	(8724, 'Webb Candy', 'Peppermint Candy Cane Lip Balm', 'Webb Candy', NULL, NULL),
	(8764, 'Shopko Chest Congestion Relief DMTDM', 'Dextromethorphan Hydrobromide / Guaifenesin', 'Shopko', NULL, NULL),
	(8784, 'Standardized Mite, Dermatophagoides pteronyssinus, Scratch or Bulk, 30000 AU per mL', 'Standardized Mite, Dermatophagoides pteronyssinus, Scratch or Bulk, 30000 AU per mL', 'Jubilant HollisterStier LLC', NULL, NULL),
	(8794, 'Midazolam Hydrochloride', 'Midazolam Hydrochloride', 'Cardinal Health', NULL, NULL),
	(8804, 'METOPROLOL TARTRATE', 'metoprolol tartrate', 'Physicians Total Care, Inc.', NULL, NULL),
	(8844, 'CARBON DIOXIDE', 'CARBON DIOXIDE', 'Norco, Inc', NULL, NULL),
	(8864, 'Isocaine', 'Mepivacaine Hydrochloride', 'Novocol Pharmaceutical of Canada, Inc.', NULL, NULL),
	(8904, 'Cholestyramine', 'cholestyramine', 'Physicians Total Care, Inc.', NULL, NULL),
	(8944, 'Lymph I', 'Echinacea, Phytolacca Decandra, Kali Iodatum, Pinus Sylvestris, Pituitary, Apis Mellifica, Aranea Diadema', 'BioActive Nutritional, Inc.', NULL, NULL),
	(8964, 'Treatment Set TS331657', 'Treatment Set TS331657', 'Antigen Laboratories, Inc.', NULL, NULL),
	(8994, 'ALFUZOSIN HYDROCHLORIDE', 'ALFUZOSIN HYDROCHLORIDE', 'Torrent Pharmaceuticals Limited', NULL, NULL),
	(9004, 'Emerald Mint Health', 'Cetylpyridinium Chloride', 'TopCo Associates LLC', NULL, NULL),
	(9034, 'Dopamine', 'Dopamine,', 'BioActive Nutritional, Inc.', NULL, NULL),
	(9064, 'Fluocinolone Acetonide', 'Fluocinolone Acetonide', 'GW Laboratories, Inc.', NULL, NULL),
	(9084, 'Relaxation Complex', 'Anacardium, Calcerea carbonica, Hypericum, Magnesia phosphorica, Piper methysticum, Ruta graveolens, Silicea', 'Nova Homeopathic Therapeutics, Inc.', NULL, NULL),
	(9094, 'Family Care Tolnaftate', 'Tolnaftate', 'united exchange corp', NULL, NULL),
	(9104, 'Dentox', 'Berberis vulgaris, Glycyrrhiza glabra, Lappa major, Phytolacca decandra, Stillingia sylvatica, Trifolium pratense, Lymph (suis), Medulla ossis (suis), Thymus (suis),', 'Apotheca Company', NULL, NULL),
	(9114, 'Toms Wicked Fresh Spearmint Ice', 'Sodium Monofluorophosphate', 'Tom\'s of Maine, Inc.', NULL, NULL),
	(9144, 'Acetaminophen and Codeine', 'Acetaminophen and Codeine', 'REMEDYREPACK INC.', NULL, NULL),
	(9164, 'Tramadol Hydrochloride and Acetaminophen', 'tramadol hydrochloride and acetaminophen', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', NULL, NULL),
	(9194, 'vancomycin hydrochloride', 'vancomycin hydrochloride', 'Alvogen, Inc.', NULL, NULL),
	(9204, 'ENALAPRIL MALEATE', 'ENALAPRIL MALEATE', 'PD-Rx Pharmaceuticals, Inc.', NULL, NULL),
	(9264, 'Valtrum Soothing Topical Analgesic', 'camphor, menthol', 'Drogefar C.A.', NULL, NULL),
	(9274, 'Ultra-TechneKow', 'Technetium Tc-99m Generator', 'Mallinckrodt Inc.', NULL, NULL),
	(9284, 'Risedronate Sodium', 'risedronate sodium', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(9294, 'MENEST', 'esterified estrogens', 'Monarch Pharmaceuticals, Inc.', NULL, NULL),
	(9304, 'Atropine Sulfate', 'ATROPINE SULFATE', 'Hospira, Inc.', NULL, NULL),
	(9314, 'Antibacterial Protective Hand', 'Chlorhexidine Gluconate', 'Hanover Pen Corp dba HPC Global', NULL, NULL),
	(9334, 'hydroxyzine pamoate', 'hydroxyzine pamoate', 'REMEDYREPACK INC.', NULL, NULL),
	(9354, 'RE-PB HYOS ELIXIR', 'BELLADONNA ALKALOIDS W/ PHENOBARBITAL', 'Rebel Distributors Corp', NULL, NULL),
	(9364, 'Protective and Moisturizing Skin', 'Clotrimazole', 'Eduard Gerlach GmbH', NULL, NULL),
	(9414, 'topcare hemorrhoidal', 'glycerin, phenylephrine HCl, pramoxine HCl, white petrolatum', 'Topco Associates LLC', NULL, NULL),
	(9424, 'Walgreens Aloe Vera Burn Relief', 'LIDOCAINE HYDROCHLORIDE', 'WALGREEN CO.', NULL, NULL),
	(9434, 'Fluvoxamine Maleate', 'fluvoxamine maleate', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(9474, 'EndoPure Pro', 'L Arginine, Pineal, Pituitary, Progesteronium, Belladonna, Chelidonium Majus, Dioscorea Villosa, Folliculinum', 'The Wellness Center', NULL, NULL),
	(9494, 'Renvela', 'SEVELAMER CARBONATE', 'Carilion Materials Management', NULL, NULL),
	(9524, 'Medi-first Ivy-Rid First Aid', 'benzocaine and benzethonium chloride', 'Unifirst First Aid Corporation', NULL, NULL),
	(9534, 'Glytone Acne', 'benzoyl peroxide', 'Genesis Pharmaceutical, Inc.', NULL, NULL),
	(9544, 'Progena', 'Arsenicum Album, Belladonna, Calcarea Fluorica, Calcarea Sulphurica, Echinacea, Hepar Sulphuris Calcareum, Lachesis Mutus, Nux Moschata, Silicea, Sulphur Iodatum, Thymus Gland', 'Meditrend, Inc. DBA Progena Professional Formulations', NULL, NULL),
	(9624, 'Retadolor', 'Menthol and Camphor (Synthetic)', 'Concept Laboratories, Inc.', NULL, NULL),
	(9654, 'Nitrofurantoin Monohydrate/Macrocrystals', 'Nitrofurantoin Monohydrate and Nitrofurantoin, macrocrystalline', 'Mylan Pharmaceuticals Inc.', NULL, NULL),
	(9674, 'ISOVUE', 'IOPAMIDOL', 'Bracco Diagnostics Inc', NULL, NULL),
	(9734, 'Glandulae suprarenales 6', 'Glandulae suprarenales 6', 'Uriel Pharmacy Inc.', NULL, NULL),
	(9784, 'OATS FOOD', 'oat', 'Allergy Laboratories, Inc.', NULL, NULL),
	(9814, 'Diclofenac Sodium', 'Diclofenac Sodium', 'Aphena Pharma Solutions - Tennessee, Inc.', NULL, NULL),
	(9844, 'CLEAN IT ZERO RADIANCE', 'Mineral Oil', 'F&CO Co., Ltd.', NULL, NULL),
	(9874, 'HYDROXYZINE HYDROCHLORIDE', 'HYDROXYZINE HYDROCHLORIDE', 'American Health Packaging', NULL, NULL),
	(9884, 'Famotidine', 'Famotidine', 'Chain Drug Marketing Association Inc.', NULL, NULL),
	(9894, 'Tendon Rescue', 'Bryonia, Ruta Graveolens, Bellis Perennis, Argentum Metallicum', 'Peaceful Mountain, Inc.', NULL, NULL),
	(9904, 'Norco', 'Hydrocodone Bitartate and Acetaminophen', 'Actavis Pharma, Inc.', NULL, NULL),
	(9914, 'ENDODAN', 'Oxycodone and Aspirin Tablets', 'Endo Pharmaceuticals Inc', NULL, NULL),
	(9944, 'Category V', 'Immune System Booster', 'Vitality Works, Inc,', NULL, NULL),
	(9994, 'RIFAMPIN', 'RIFAMPIN', 'Major Pharmaceuticals', NULL, NULL);

CREATE TABLE IF NOT EXISTS `doctors` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `university` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `password_digest` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_doctors_on_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=1014 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO `doctors` (`id`, `name`, `university`, `created_at`, `updated_at`, `username`, `password_digest`) VALUES
	(4, 'Tadd Norcross', 'Missouri Valley College', NULL, NULL, 'tnorcross0', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(14, 'Rollie Bourcq', 'College of the Ozarks', NULL, NULL, 'rbourcq1', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(24, 'Mariejeanne Ciubutaro', 'Birmingham City University', NULL, NULL, 'mciubutaro2', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(34, 'Daisie de Voiels', 'Jingdezhen China Institute', NULL, NULL, 'dde3', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(44, 'Rafael Mead', 'Islamic Azad University, Dehaghan', NULL, NULL, 'rmead4', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(54, 'Stearn Brosius', 'Hiroshima Shudo University', NULL, NULL, 'sbrosius5', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(64, 'Fax Bare', 'Universidad Galileo', NULL, NULL, 'fbare6', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(74, 'Ellen Merner', 'Universidad Miguel Hernández de Elche', NULL, NULL, 'emerner7', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(84, 'Elita Jodrellec', 'Nagaland University', NULL, NULL, 'ejodrellec8', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(94, 'Thedric Walder', 'Virginia Polytechnic Institute and State University (Virginia Tech)', NULL, NULL, 'twalder9', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(104, 'Ivar Sedgebeer', 'Polytechnic University', NULL, NULL, 'isedgebeera', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(114, 'Adiana Sidworth', 'John Marshall Law School', NULL, NULL, 'asidworthb', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(124, 'Derwin Gaskin', 'Universitas Simalungun', NULL, NULL, 'dgaskinc', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(134, 'Aldous Chaperlin', 'Bindura University of Science Education', NULL, NULL, 'achaperlind', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(144, 'Pearla Tatton', 'Andrassy Gyula German Speaking University Budapest', NULL, NULL, 'ptattone', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(154, 'Urbain Gonnard', 'Dickinson College', NULL, NULL, 'ugonnardf', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(164, 'Tasha Kayley', 'Centre d\'Etudes Supérieures des Techniques Industrielles', NULL, NULL, 'tkayleyg', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(174, 'Cassy Leggen', 'Tokyo University of Pharmacy and Life Science', NULL, NULL, 'cleggenh', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(184, 'Davida Osmint', 'Antioch New England Graduate School', NULL, NULL, 'dosminti', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(194, 'Welch Flag', 'Universitas Ibn Khaldun Bogor', NULL, NULL, 'wflagj', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(204, 'Sanderson Crittal', 'Universidad Autónoma de Centro América', NULL, NULL, 'scrittalk', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(214, 'Robinet Adamthwaite', 'Montanuniversität Leoben', NULL, NULL, 'radamthwaitel', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(224, 'Sindee Bockler', 'Kazak National Technical University', NULL, NULL, 'sbocklerm', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(234, 'Julie Cawston', 'Universitas Wisnuwardhana', NULL, NULL, 'jcawstonn', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(244, 'Geri Kemmet', 'Universidad Evangélica de El Salvador', NULL, NULL, 'gkemmeto', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(254, 'Edy Kobpal', 'Kagoshima University', NULL, NULL, 'ekobpalp', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(264, 'Gregoor Hutchinson', 'Kanagawa University', NULL, NULL, 'ghutchinsonq', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(274, 'Lindsey Tottie', 'Schiller International University, American College of Switzerland', NULL, NULL, 'ltottier', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(284, 'Husein Darrel', 'Universidade Federal Rural do Rio de Janeiro', NULL, NULL, 'hdarrels', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(294, 'Tally Ventura', 'Universidade de Ribeirão Preto', NULL, NULL, 'tventurat', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(304, 'Marylynne Baguley', 'Universitas Padjadjaran', NULL, NULL, 'mbaguleyu', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(314, 'Alistair Epton', 'Fukuoka Prefectural University', NULL, NULL, 'aeptonv', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(324, 'Catherina Peagrim', 'Shobhit University, Meerut', NULL, NULL, 'cpeagrimw', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(334, 'Zelma Swadlin', 'Ivano-Frankivsk National University of Oli and Gas', NULL, NULL, 'zswadlinx', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(344, 'Ermina Trimming', 'Rivers State University of Science and Technology', NULL, NULL, 'etrimmingy', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(354, 'Nixie Garbett', 'Auburn University', NULL, NULL, 'ngarbettz', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(364, 'Kinnie Mather', 'Rosemont College', NULL, NULL, 'kmather10', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(374, 'Hedy Kildahl', 'Shahrekord University of Medical Sciences', NULL, NULL, 'hkildahl11', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(384, 'Carlos Goodson', 'University of Ghana', NULL, NULL, 'cgoodson12', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(394, 'Kettie Jaques', 'Kurdistan University of Medical Sciences', NULL, NULL, 'kjaques13', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(404, 'Wyatan Goutcher', 'Islamic Azad University, Shirvan', NULL, NULL, 'wgoutcher14', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(414, 'Robinett Greenhaugh', 'Kotelawala Defence University', NULL, NULL, 'rgreenhaugh15', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(424, 'Mackenzie Mathivet', 'Universidad Popular Autonóma del Estado de Puebla', NULL, NULL, 'mmathivet16', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(434, 'Nonie Swyer', 'Southern Alberta Institute of Technology', NULL, NULL, 'nswyer17', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(444, 'Budd Hughf', 'Johore Bharu Primeir Polytechnic', NULL, NULL, 'bhughf18', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(454, 'Shandy Stonehewer', 'Orissa University of Agriculture and Technology', NULL, NULL, 'sstonehewer19', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(464, 'Wilburt Binney', 'Universidad de Guanajuato, Campus León', NULL, NULL, 'wbinney1a', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(474, 'Melodie Shedd', 'Orkhon University', NULL, NULL, 'mshedd1b', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(484, 'Abbye Dawton', 'Armenian State University of Economics', NULL, NULL, 'adawton1c', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(494, 'Vanda Meneghelli', 'Concordia University, River Forest', NULL, NULL, 'vmeneghelli1d', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(504, 'Bartholemy Farge', 'Aristotle University of Thessaloniki', NULL, NULL, 'bfarge1e', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(514, 'Milzie Sinclair', 'Osaka University of Foreign Studies', NULL, NULL, 'msinclair1f', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(524, 'Wendeline Jerson', 'Indian Institute of Technology, Roorkee', NULL, NULL, 'wjerson1g', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(534, 'Othelia de Merida', 'VBS Purvanchal University', NULL, NULL, 'ode1h', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(544, 'Sansone Moverley', 'Universidad Santa Maria Caracas', NULL, NULL, 'smoverley1i', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(554, 'Clarey Crudge', 'Xuzhou Normal University', NULL, NULL, 'ccrudge1j', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(564, 'Kelbee Cockton', 'University of Toronto, Scarborough', NULL, NULL, 'kcockton1k', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(574, 'Igor Plak', 'Institute of Business & Technology', NULL, NULL, 'iplak1l', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(584, 'Lyn Djorevic', 'University of Northampton', NULL, NULL, 'ldjorevic1m', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(594, 'Kean Doudny', 'Black Hills State University', NULL, NULL, 'kdoudny1n', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(604, 'Nevile Toke', 'Khazar University', NULL, NULL, 'ntoke1o', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(614, 'Nell Flook', 'Middle Tennessee State University', NULL, NULL, 'nflook1p', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(624, 'Agnes Farnorth', 'Polonia University in Czêstochowa', NULL, NULL, 'afarnorth1q', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(634, 'Des Mingo', 'Universidad ICESI', NULL, NULL, 'dmingo1r', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(644, 'Lyndell Bramble', 'Instituto Politécnico de Beja', NULL, NULL, 'lbramble1s', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(654, 'Chrissy Keeley', 'Akita University of Economics and Law', NULL, NULL, 'ckeeley1t', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(664, 'Thaddus O\'Spellissey', 'Centre Universitaire de Technologie', NULL, NULL, 'tospellissey1u', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(674, 'Malcolm Paling', 'Ecole Normale Supérieure de Paris', NULL, NULL, 'mpaling1v', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(684, 'Shannon Eymer', 'Gezira College of Technology', NULL, NULL, 'seymer1w', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(694, 'Liesa Vittel', 'Universidad Autónoma Latinoamericana', NULL, NULL, 'lvittel1x', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(704, 'Irina Tipper', 'Institute of Textile Technology', NULL, NULL, 'itipper1y', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(714, 'Yanaton Messier', 'Morris College', NULL, NULL, 'ymessier1z', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(724, 'Enrico Livingstone', 'College Misericordia', NULL, NULL, 'elivingstone20', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(734, 'Lynett Ranald', 'Kanazawa Institute of Technology', NULL, NULL, 'lranald21', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(744, 'Eda McCraw', 'Trident University', NULL, NULL, 'emccraw22', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(754, 'Othilia Jean', 'Omsk State Technical University', NULL, NULL, 'ojean23', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(764, 'Eadith Sparrowe', 'National Taipei University of Technology', NULL, NULL, 'esparrowe24', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(774, 'Rahel Tunnacliffe', 'Indira Gandhi Institute of Development and Research', NULL, NULL, 'rtunnacliffe25', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(784, 'Josy Yanez', 'Jagannath University', NULL, NULL, 'jyanez26', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(794, 'Allx MacInherney', 'Kumasi Polytechnic ', NULL, NULL, 'amacinherney27', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(804, 'Gunar Roundtree', 'Southern Connecticut State University', NULL, NULL, 'groundtree28', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(814, 'Ariel Smallcombe', 'Universidad Nacional de Santiago del Estero', NULL, NULL, 'asmallcombe29', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(824, 'Kessia Label', 'Universidad Tecnologica Israel', NULL, NULL, 'klabel2a', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(834, 'Sky Mottershaw', 'Ecole Nationale Supérieure d\'Electronique, d\'Electrotechnique, d\'Informatique et d\'Hydraulique de Toulouse', NULL, NULL, 'smottershaw2b', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(844, 'Geordie Bianco', 'Fresno City College', NULL, NULL, 'gbianco2c', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(854, 'Binny MacEveley', 'Mary Baldwin College', NULL, NULL, 'bmaceveley2d', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(864, 'Murry Hagley', 'Universidade do Rio Grande', NULL, NULL, 'mhagley2e', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(874, 'Kendal Landis', 'Universidade Federal da Grande Dourados', NULL, NULL, 'klandis2f', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(884, 'Dulcie Tabb', 'Universidad Nacional de Cajamarca', NULL, NULL, 'dtabb2g', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(894, 'Gnni Kubacek', 'Alfred Nobel University of Economics and Law ', NULL, NULL, 'gkubacek2h', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(904, 'Armando Corre', 'University of Charleston South Carolina', NULL, NULL, 'acorre2i', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(914, 'Ardath Shrimpling', 'Penza State University', NULL, NULL, 'ashrimpling2j', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(924, 'Karmen Philippe', 'Université du Québec à Montréal', NULL, NULL, 'kphilippe2k', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(934, 'Cari Duffie', 'Capital University', NULL, NULL, 'cduffie2l', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(944, 'Carolee Colwell', 'Adventist University of the Philippines', NULL, NULL, 'ccolwell2m', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(954, 'Gennifer Popping', 'COMSATS Institute of Information Technology, Attock', NULL, NULL, 'gpopping2n', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(964, 'Marven Riddiford', 'Tajikistan International University', NULL, NULL, 'mriddiford2o', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(974, 'Tully Dignam', 'Ohio Wesleyan University', NULL, NULL, 'tdignam2p', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(984, 'Benetta Headly', 'Institute of Latin American Studies, University of London', NULL, NULL, 'bheadly2q', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe'),
	(994, 'Francklyn Montford', 'Dunya Institute of Higher Education', NULL, NULL, 'fmontford2r', '$2a$12$1q91PdiuvEmR1USq8Kb1Muy1TE0YAq319wKS62aWm60RSgMJQ2zCe');
	
CREATE TABLE IF NOT EXISTS `patients` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1014 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO `patients` (`id`, `name`, `age`, `gender`, `created_at`, `updated_at`) VALUES
	(4, 'Griff Lethardy', 22, 'X', NULL, NULL),
	(14, 'Tabitha Dyett', 63, 'X', NULL, NULL),
	(24, 'Arabela Brodley', 61, 'M', NULL, NULL),
	(34, 'Valaree Dawltrey', 58, 'M', NULL, NULL),
	(44, 'Ashlan Ludl', 43, 'X', NULL, NULL),
	(54, 'Allianora Allington', 53, 'X', NULL, NULL),
	(64, 'Cosme Joris', 46, 'M', NULL, NULL),
	(74, 'Lucy Knellen', 18, 'M', NULL, NULL),
	(84, 'Sinclair Twiname', 28, 'X', NULL, NULL),
	(94, 'Cathyleen Crankhorn', 60, 'X', NULL, NULL),
	(104, 'Sayres Sulter', 63, 'X', NULL, NULL),
	(114, 'Quent Longdon', 51, 'X', NULL, NULL),
	(124, 'Spike Solan', 66, 'M', NULL, NULL),
	(134, 'Cassaundra Picton', 41, 'M', NULL, NULL),
	(144, 'Elena Yurin', 31, 'X', NULL, NULL),
	(154, 'Dix Aiston', 40, 'X', NULL, NULL),
	(164, 'Stormy Benes', 62, 'X', NULL, NULL),
	(174, 'Denys Ivanikov', 47, 'X', NULL, NULL),
	(184, 'Renault Gill', 24, 'X', NULL, NULL),
	(194, 'Gibby Gypps', 53, 'X', NULL, NULL),
	(204, 'Ernesta Holleran', 69, 'X', NULL, NULL),
	(214, 'Teri Lissenden', 55, 'X', NULL, NULL),
	(224, 'Clarey Karpets', 63, 'X', NULL, NULL),
	(234, 'Jerrie Emmett', 33, 'X', NULL, NULL),
	(244, 'Martainn Dyett', 46, 'M', NULL, NULL),
	(254, 'Erena Bodleigh', 60, 'F', NULL, NULL),
	(264, 'Nelie Glendinning', 49, 'X', NULL, NULL),
	(274, 'Wallache Benedick', 55, 'X', NULL, NULL),
	(284, 'Hildegarde MacBrearty', 34, 'X', NULL, NULL),
	(294, 'Alena Fadell', 66, 'F', NULL, NULL),
	(304, 'Darnall Deacon', 56, 'M', NULL, NULL),
	(314, 'Uta Dymock', 23, 'M', NULL, NULL),
	(324, 'Isabel Tommasuzzi', 61, 'X', NULL, NULL),
	(334, 'Ali Sprakes', 34, 'M', NULL, NULL),
	(344, 'Silvia Martinyuk', 66, 'F', NULL, NULL),
	(354, 'Stavro M\'Quharge', 51, 'X', NULL, NULL),
	(364, 'Doroteya Speers', 54, 'M', NULL, NULL),
	(374, 'Carleen Barz', 34, 'M', NULL, NULL),
	(384, 'Bernice Scutts', 64, 'M', NULL, NULL),
	(394, 'Glenn Cazereau', 65, 'X', NULL, NULL),
	(404, 'Caril Laing', 44, 'X', NULL, NULL),
	(414, 'Ashby Byrnes', 45, 'X', NULL, NULL),
	(424, 'Bianka Staves', 55, 'F', NULL, NULL),
	(434, 'Sybila Laughnan', 30, 'F', NULL, NULL),
	(444, 'Elsy Shakesbye', 35, 'M', NULL, NULL),
	(454, 'Feodor Hubbuck', 49, 'F', NULL, NULL),
	(464, 'Maureene Petzold', 20, 'M', NULL, NULL),
	(474, 'Vernor Varney', 56, 'X', NULL, NULL),
	(484, 'Eden Comberbeach', 34, 'F', NULL, NULL),
	(494, 'Helyn Dellenty', 40, 'X', NULL, NULL),
	(504, 'Forrest Crocker', 24, 'X', NULL, NULL),
	(514, 'Jerry Donati', 25, 'X', NULL, NULL),
	(524, 'Tanny Gribbins', 47, 'X', NULL, NULL),
	(534, 'Sharron Battrum', 35, 'F', NULL, NULL),
	(544, 'Kat Merredy', 43, 'X', NULL, NULL),
	(554, 'Shirley Hardes', 38, 'X', NULL, NULL),
	(564, 'Randi Bosanko', 66, 'F', NULL, NULL),
	(574, 'Jerald Peat', 46, 'M', NULL, NULL),
	(584, 'Netta O\'Corhane', 28, 'X', NULL, NULL),
	(594, 'Aubert Aucoate', 33, 'F', NULL, NULL),
	(604, 'Barbabra Martinello', 20, 'M', NULL, NULL),
	(614, 'Sharai Brahms', 48, 'F', NULL, NULL),
	(624, 'Ellery Peckitt', 35, 'M', NULL, NULL),
	(634, 'Charis Luckett', 64, 'X', NULL, NULL),
	(644, 'Kacy Simmens', 52, 'F', NULL, NULL),
	(654, 'Anne Estcot', 50, 'X', NULL, NULL),
	(664, 'Antin Fishburn', 25, 'F', NULL, NULL),
	(674, 'Katheryn Charlin', 35, 'M', NULL, NULL),
	(684, 'Paulie Di Biagi', 54, 'X', NULL, NULL),
	(694, 'Tarra Howett', 32, 'X', NULL, NULL),
	(704, 'Dov Stait', 24, 'X', NULL, NULL),
	(714, 'Karee Greenlees', 43, 'X', NULL, NULL),
	(724, 'Mariya Lucius', 60, 'M', NULL, NULL),
	(734, 'Ursulina Lyver', 42, 'X', NULL, NULL),
	(744, 'Alaine Goodswen', 53, 'X', NULL, NULL),
	(754, 'Zorina Perazzo', 60, 'X', NULL, NULL),
	(764, 'Bern Bodycote', 32, 'F', NULL, NULL),
	(774, 'Caitlin Etuck', 65, 'M', NULL, NULL),
	(784, 'Sisile Weddeburn', 39, 'M', NULL, NULL),
	(794, 'Hestia Pyner', 43, 'F', NULL, NULL),
	(804, 'Dulcinea Moult', 22, 'X', NULL, NULL),
	(814, 'Ivie Castanho', 19, 'F', NULL, NULL),
	(824, 'Quillan Dmitrienko', 46, 'X', NULL, NULL),
	(834, 'Reeva Fordyce', 31, 'X', NULL, NULL),
	(844, 'Amble Doorey', 44, 'F', NULL, NULL),
	(854, 'Eduino Mion', 35, 'M', NULL, NULL),
	(864, 'Lyell Denny', 36, 'M', NULL, NULL),
	(874, 'Barny Kubas', 46, 'F', NULL, NULL),
	(884, 'Pegeen Sanches', 45, 'F', NULL, NULL),
	(894, 'Broderick Crusham', 60, 'F', NULL, NULL),
	(904, 'Leanor Downing', 35, 'F', NULL, NULL),
	(914, 'Diana Ohanessian', 27, 'M', NULL, NULL),
	(924, 'Ericha Schoffler', 22, 'X', NULL, NULL),
	(934, 'Alfie Gamlin', 65, 'F', NULL, NULL),
	(944, 'Jeanine Everett', 68, 'X', NULL, NULL),
	(954, 'Zared Sandercock', 47, 'M', NULL, NULL),
	(964, 'Kristofor Flexman', 64, 'M', NULL, NULL),
	(974, 'Barron Eades', 39, 'F', NULL, NULL),
	(984, 'Cathrine Louth', 55, 'M', NULL, NULL),
	(994, 'Abbe Gounot', 37, 'X', NULL, NULL);

CREATE TABLE IF NOT EXISTS `consultations` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `diagnosis` varchar(255) DEFAULT NULL,
  `procedure` varchar(255) DEFAULT NULL,
  `drug_id` bigint(20) NOT NULL,
  `patient_id` bigint(20) NOT NULL,
  `doctor_id` bigint(20) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_consultations_on_drug_id` (`drug_id`),
  KEY `index_consultations_on_patient_id` (`patient_id`),
  KEY `index_consultations_on_doctor_id` (`doctor_id`),
  CONSTRAINT `fk_rails_33c52f1c05` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`),
  CONSTRAINT `fk_rails_b1f629cdac` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`id`),
  CONSTRAINT `fk_rails_d0a5f61ace` FOREIGN KEY (`drug_id`) REFERENCES `drugs` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10014 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

INSERT INTO `consultations` (`id`, `diagnosis`, `procedure`, `drug_id`, `patient_id`, `doctor_id`, `created_at`, `updated_at`) VALUES
	(664, 'Cerebral infarction due to thrombosis of left carotid artery', 'Repair Coronary Vein, Percutaneous Approach', 694, 74, 4, NULL, NULL),
	(1664, 'Other traumatic displaced spondylolisthesis of sixth cervical vertebra, subsequent encounter for fracture with nonunion', 'Revision of Nonautologous Tissue Substitute in Left Eye, Via Natural or Artificial Opening Endoscopic', 324, 44, 74, NULL, NULL),
	(9694, 'Unspecified injury of unspecified renal vein', 'Dilation of Left Temporal Artery with Four or More Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach', 354, 4, 34, NULL, NULL);